// tiles_renderer SDK implementation.
//
// P2: real Filament rendering on Linux (OpenGL backend, native X11/Wayland
// window handle). P4: the same engine/scene/view code now runs on Android
// (Vulkan + ANativeWindow), Windows (Vulkan + HWND), iOS (Metal + UIView)
// and Web (WebGL + canvas selector) — only the backend enum and the native
// handle interpretation differ per platform (see TILES_FILAMENT_BACKEND).

#include "tiles_renderer/renderer.h"

#include "tiles_renderer/version.h"
#include "tileset_internal.h"

#include <atomic>
#include <chrono>
#include <iostream>
#include <memory>
#include <thread>

#ifdef TILES_WITH_FILAMENT
#include <backend/PixelBufferDescriptor.h>
#include <filament/Camera.h>
#include <filament/Engine.h>
#include <filament/IndexBuffer.h>
#include <filament/IndirectLight.h>
#include <filament/LightManager.h>
#include <filament/Material.h>
#include <filament/RenderableManager.h>
#include <filament/Renderer.h>
#include <filament/Scene.h>
#include <filament/SwapChain.h>
#include <filament/Texture.h>
#include <filament/VertexBuffer.h>
#include <filament/View.h>
#include <filament/Viewport.h>
#include <utils/EntityManager.h>

#include <cmath>
#include <vector>

#include "unlit_color_filamat.h" // generated by cmake/embed_filamat.py (matc)
#endif

// P4: platform backend selection. TILES_PLATFORM_* is defined by CMake from
// the TILES_PLATFORM cache variable, so the choice follows the *target*
// platform rather than host compiler macros (matters for cross builds).
//
// Backend choice follows what each official Filament prebuilt ships:
//   linux   : OpenGL (X11 Window / wl_surface* as void*)
//   android : Vulkan (ANativeWindow*; android prebuilt ships bluevk only)
//   windows : Vulkan (HWND)
//   ios     : Metal (UIView*)
#ifdef TILES_WITH_FILAMENT
#if defined(TILES_PLATFORM_ANDROID)
#define TILES_FILAMENT_BACKEND filament::Engine::Backend::VULKAN
#define TILES_PLATFORM_NAME "Android/Vulkan"
#elif defined(TILES_PLATFORM_WINDOWS)
#define TILES_FILAMENT_BACKEND filament::Engine::Backend::VULKAN
#define TILES_PLATFORM_NAME "Windows/Vulkan"
#elif defined(TILES_PLATFORM_IOS)
#define TILES_FILAMENT_BACKEND filament::Engine::Backend::METAL
#define TILES_PLATFORM_NAME "iOS/Metal"
#elif defined(TILES_PLATFORM_LINUX)
#define TILES_FILAMENT_BACKEND filament::Engine::Backend::OPENGL
#define TILES_PLATFORM_NAME "Linux/OpenGL"
#else
#error "TILES_PLATFORM_*: unknown target platform (expected CMake to define one)"
#endif
#endif // TILES_WITH_FILAMENT

namespace tiles_renderer {
namespace {

// P19: cache budget set before any tileset is loaded is stashed here and
// applied in loadTileset() before the cesium Tileset is constructed.
// P22-hotfix: this is a plain std::int64_t with no Filament dependency, so
// it lives OUTSIDE the TILES_WITH_FILAMENT guard — setMaxCachedBytes()
// references it unconditionally (a Filament-OFF build once failed here
// with "use of undeclared identifier", P22 CI).
std::int64_t g_pendingMaxCachedBytes = -1;

// P31: pending live SSE override (setMaximumScreenSpaceError before any
// tileset is loaded). g_hasPendingMaxSse tracks "explicitly set" so a
// negative stash (documented as "restore default 16") is not confused
// with "never set". Same unguarded placement rule as
// g_pendingMaxCachedBytes above.
double g_pendingMaxSse = 16.0;
bool g_hasPendingMaxSse = false;

// P32: event callbacks registered via setEventCallbacks(). Persist across
// loadTileset() calls (and shutdown, like the other stashed settings);
// forwarded to each new TilesetRenderer at load.
Renderer::TilesetEventCallbacks g_eventCallbacks;

// P33: show / preloadWhenHidden / modelMatrix stash. Persist across
// loadTileset() calls; forwarded to each new TilesetRenderer at load.
// The matrix is stored column-major (matches the public API).
bool g_show = true;
// CESIUM_primitive_outline stashed switches (pre-load).
bool g_enableShowOutline = true;
bool g_showOutline = true;
float g_outlineColor[3] = {0.0f, 0.0f, 0.0f};
bool g_preloadWhenHidden = false;
double g_modelMatrix[16] = {1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
                            0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0};
// P35: debug switches stashed across loadTileset() calls; forwarded to
// each new TilesetRenderer at load. P36: split volume flags + freeze frame
// + overlay callback.
bool g_debugShowBoundingVolume = false;
bool g_debugShowContentBoundingVolume = false;
bool g_debugShowViewerRequestVolume = false;
bool g_debugShowUrl = false;
bool g_debugFreezeFrame = false;
Renderer::OverlayCallback g_overlayCallback;

#ifdef TILES_WITH_FILAMENT

// P2 demo geometry: a single triangle. Static storage so the Filament buffer
// descriptors never dangle.
constexpr filament::math::float3 kTriangleVerts[3] = {
    {-0.6f, -0.5f, 0.0f},
    {0.6f, -0.5f, 0.0f},
    {0.0f, 0.6f, 0.0f},
};
constexpr std::uint16_t kTriangleIndices[3] = {0, 1, 2};

// ---------------------------------------------------------------------------
// P26: default image-based lighting.
//
// Before P26 the scene's only light was the P3 directional sun, so metals
// could only show the sun's specular lobe and were otherwise black
// (ADR-0013). We now add a Filament IndirectLight driven by a small
// *procedural* environment, generated deterministically at initialize():
//
// - 6 cubemap faces (64x64 RGBA8) from an analytic sky-gradient + sun
//   function; mipmaps generated on the GPU via Texture::generateMipmaps.
//   These feed the specular (reflections) part. Note: plain box-filtered
//   mips, not cmgen-quality GGX prefiltering — plausible for a default
//   outdoor environment; the tradeoff is documented in ADR-0025.
// - Diffuse irradiance as 3-band spherical harmonics of the same analytic
//   function (deterministic Fibonacci-sphere quadrature), passed via
//   IndirectLight::Builder::radiance(), which does the irradiance
//   convolution/scaling internally.
//
// Why procedural instead of an embedded .ktx: zero new dependencies, zero
// binary blobs, identical on every platform (pure Filament core API), and
// bit-deterministic. The sun blob sits at the direction *toward* the sun,
// matching the P3 directional light (whose .direction() is the direction
// light travels).
// ---------------------------------------------------------------------------
namespace default_ibl {

using filament::math::float3;

// 64x64 per face: 96KB total, generated once at initialize().
constexpr std::uint32_t kFaceSize = 64;

// Direction *toward* the procedural sun: normalize(-(0,-1,0.35)), the
// opposite of the P3 directional light's travel direction.
inline float3 sunDirection() {
    float3 d{0.0f, 1.0f, -0.35f};
    return d / length(d);
}

// Analytic outdoor environment (linear-space radiance, y-up). Deterministic:
// pure function of direction, no RNG, no tables.
float3 envRadiance(const float3& d) {
    const float sunDot = std::max(dot(d, sunDirection()), 0.0f);
    const float up = std::min(std::max(d.y, 0.0f), 1.0f);
    const float down = std::min(std::max(-d.y, 0.0f), 1.0f);
    // Sky: horizon -> zenith gradient; ground: dark.
    const float3 horizon{0.40f, 0.50f, 0.70f};
    const float3 zenith{0.09f, 0.15f, 0.34f};
    const float3 ground{0.08f, 0.075f, 0.07f};
    const float su = up * up * (3.0f - 2.0f * up); // smoothstep
    const float sd = down * down * (3.0f - 2.0f * down);
    const float3 base = d.y >= 0.0f ? horizon + (zenith - horizon) * su
                                    : horizon + (ground - horizon) * sd;
    // Sun disc + glow. Values above 1.0 clip on the RGBA8 upload; the disc
    // stays the brightest feature, which is what matters for reflections.
    const float disc =
        std::min(std::max((sunDot - 0.9993f) / 0.0004f, 0.0f), 1.0f);
    const float glow =
        std::pow(sunDot, 700.0f) * 0.55f + std::pow(sunDot, 24.0f) * 0.10f;
    return base + float3{1.0f, 0.97f, 0.90f} * (disc * 0.9f + glow);
}

// Cubemap face order used by Filament (see filament::FaceOffsets in the
// filament-generatePrefilterMipmap headers): +X, -X, +Y, -Y, +Z, -Z.
// Direction per face follows the OpenGL cubemap convention; (u, v) are the
// texel's normalized coordinates in [-1, 1], v = -1 at the first buffer row.
float3 faceDirection(int face, float u, float v) {
    const float s = u, t = v;
    float3 d{0.0f, 0.0f, 0.0f};
    switch (face) {
        case 0: d = float3{1.0f, -t, -s}; break;  // +X
        case 1: d = float3{-1.0f, -t, s}; break;  // -X
        case 2: d = float3{s, 1.0f, t}; break;    // +Y
        case 3: d = float3{s, -1.0f, -t}; break;  // -Y
        case 4: d = float3{s, -t, 1.0f}; break;   // +Z
        default: d = float3{-s, -t, -1.0f}; break; // -Z
    }
    return d / length(d);
}

// Real spherical-harmonics basis, graphics convention (no Condon-Shortley
// phase), index(l, m) = l * (l + 1) + m as documented in IndirectLight.h.
void shBasis(const float3& d, float* b /*[9]*/) {
    const float x = d.x, y = d.y, z = d.z;
    b[0] = 0.282095f;
    b[1] = 0.488603f * y;
    b[2] = 0.488603f * z;
    b[3] = 0.488603f * x;
    b[4] = 1.092548f * x * y;
    b[5] = 1.092548f * y * z;
    b[6] = 0.315392f * (3.0f * z * z - 1.0f);
    b[7] = 1.092548f * x * z;
    b[8] = 0.546274f * (x * x - y * y);
}

// Project envRadiance() onto 3 SH bands by deterministic Fibonacci-sphere
// quadrature. Returns *radiance* coefficients for
// IndirectLight::Builder::radiance().
void computeRadianceSH(float3* sh /*[9]*/) {
    constexpr int kSamples = 2048;
    constexpr float kPi = 3.14159265358979323846f;
    // Golden angle pi*(3-sqrt(5)): spelled out because std::sqrt is not
    // constexpr in libc++ (NDK r27d / iOS), which broke those CI jobs.
    constexpr float kGolden = 2.3999632f;
    for (int k = 0; k < 9; ++k) {
        sh[k] = float3{0.0f, 0.0f, 0.0f};
    }
    for (int i = 0; i < kSamples; ++i) {
        const float z = 1.0f - 2.0f * (i + 0.5f) / kSamples;
        const float r = std::sqrt(std::max(0.0f, 1.0f - z * z));
        const float phi = kGolden * i;
        const float3 d{r * std::cos(phi), z, r * std::sin(phi)};
        const float3 L = envRadiance(d);
        float b[9];
        shBasis(d, b);
        for (int k = 0; k < 9; ++k) {
            sh[k] += L * b[k];
        }
    }
    const float scale = 4.0f * kPi / kSamples;
    for (int k = 0; k < 9; ++k) {
        sh[k] *= scale;
    }
}

struct BuiltIbl {
    filament::IndirectLight* light = nullptr;
    filament::Texture* reflections = nullptr;
};

// Build the default procedural IBL. Any failure returns {nullptr, nullptr}
// and the caller keeps sun-only lighting.
BuiltIbl build(filament::Engine& engine) {
    BuiltIbl out;
    filament::Texture* tex = filament::Texture::Builder()
                                 .width(kFaceSize)
                                 .height(kFaceSize)
                                 .levels(0xff)
                                 .usage(filament::Texture::Usage::DEFAULT |
                                        filament::Texture::Usage::GEN_MIPMAPPABLE)
                                 .format(filament::Texture::InternalFormat::RGBA8)
                                 .sampler(filament::Texture::Sampler::SAMPLER_CUBEMAP)
                                 .build(engine);
    if (tex == nullptr) {
        return out;
    }
    for (int face = 0; face < 6; ++face) {
        auto* px = new std::uint8_t[kFaceSize * kFaceSize * 4];
        for (std::uint32_t y = 0; y < kFaceSize; ++y) {
            for (std::uint32_t x = 0; x < kFaceSize; ++x) {
                const float u = 2.0f * (x + 0.5f) / kFaceSize - 1.0f;
                const float v = 2.0f * (y + 0.5f) / kFaceSize - 1.0f;
                const float3 L = envRadiance(faceDirection(face, u, v));
                std::uint8_t* p = px + (y * kFaceSize + x) * 4;
                p[0] = (std::uint8_t)(std::min(std::max(L.x, 0.0f), 1.0f) * 255.0f + 0.5f);
                p[1] = (std::uint8_t)(std::min(std::max(L.y, 0.0f), 1.0f) * 255.0f + 0.5f);
                p[2] = (std::uint8_t)(std::min(std::max(L.z, 0.0f), 1.0f) * 255.0f + 0.5f);
                p[3] = 255;
            }
        }
        filament::Texture::PixelBufferDescriptor pbd(
            px, kFaceSize * kFaceSize * 4, filament::Texture::Format::RGBA,
            filament::Texture::Type::UBYTE,
            [](void* buf, size_t, void*) { delete[] static_cast<std::uint8_t*>(buf); });
        // Cubemap faces are selected by zoffset: 0=+X .. 5=-Z.
        tex->setImage(engine, 0, 0, 0, (std::uint32_t)face, kFaceSize,
                      kFaceSize, 1, std::move(pbd));
    }
    tex->generateMipmaps(engine);

    float3 sh[9];
    computeRadianceSH(sh);
    out.light = filament::IndirectLight::Builder()
                    .reflections(tex)
                    .radiance(3, sh)
                    .intensity(30000.0f) // Filament default; env is 0..1 LDR
                    .build(engine);
    if (out.light == nullptr) {
        engine.destroy(tex);
        return out;
    }
    out.reflections = tex;
    return out;
}

} // namespace default_ibl

struct FilamentState {
    filament::Engine* engine = nullptr;
    filament::SwapChain* swapChain = nullptr;
    filament::Renderer* renderer = nullptr; // filament::Renderer (not this SDK class)
    filament::Scene* scene = nullptr;
    filament::View* view = nullptr;
    filament::Camera* camera = nullptr;
    utils::Entity cameraEntity{};
    utils::Entity renderable{};
    filament::VertexBuffer* vertexBuffer = nullptr;
    filament::IndexBuffer* indexBuffer = nullptr;
    filament::Material* material = nullptr;
    filament::MaterialInstance* materialInstance = nullptr;
    std::uint32_t width = 0;
    std::uint32_t height = 0;
    // P12: the native window handle passed to initialize(), kept so resize()
    // can recreate the swap chain for the same window.
    void* nativeWindow = nullptr;
    // P3: optional tileset integration (null when no tileset loaded).
    std::unique_ptr<TilesetRenderer> tileset;
    OrbitCamera orbit;
    // P37-C1: explicit lookAt camera (cesium.js conformance).
    ExplicitCamera explicitCam;
    // P37-C1: clear color (default dark blue), FOV (default 45°),
    // near/far planes (default 0.1/100.0).
    float clearColor[4] = {0.1f, 0.2f, 0.45f, 1.0f};
    float fovDegrees = 45.0f; // P37-C1: default 45° (historical); use setFovDegrees() for 60°
    double nearPlane = 0.1;
    double farPlane = 100.0;
    utils::Entity sunLight{};
    // P26: default procedural IBL (IndirectLight + reflections cubemap).
    // Built once at initialize(); setIblEnabled() only toggles scene
    // membership, so the objects stay alive for the session.
    filament::IndirectLight* ibl = nullptr;
    filament::Texture* iblReflections = nullptr;
    bool iblEnabled = true;
    bool triangleInScene = false;
};

FilamentState g_state;

void destroyFilamentState() {
    FilamentState& s = g_state;
    if (s.engine == nullptr) {
        return;
    }
    // Destroy user resources first, engine last (Filament requirement).
    if (s.sunLight) {
        s.scene->remove(s.sunLight);
        s.engine->destroy(s.sunLight);
        utils::EntityManager::get().destroy(s.sunLight);
        s.sunLight.clear();
    }
    // P26: IBL must leave the scene before its objects are destroyed.
    if (s.ibl) {
        s.scene->setIndirectLight(nullptr);
        s.engine->destroy(s.ibl);
        s.ibl = nullptr;
    }
    if (s.iblReflections) {
        s.engine->destroy(s.iblReflections);
        s.iblReflections = nullptr;
    }
    s.iblEnabled = true;
    if (s.renderable) {
        if (s.triangleInScene) {
            s.scene->remove(s.renderable);
            s.triangleInScene = false;
        }
        s.engine->destroy(s.renderable);
        utils::EntityManager::get().destroy(s.renderable);
        s.renderable.clear();
    }
    if (s.materialInstance) {
        s.engine->destroy(s.materialInstance);
        s.materialInstance = nullptr;
    }
    if (s.material) {
        s.engine->destroy(s.material);
        s.material = nullptr;
    }
    if (s.vertexBuffer) {
        s.engine->destroy(s.vertexBuffer);
        s.vertexBuffer = nullptr;
    }
    if (s.indexBuffer) {
        s.engine->destroy(s.indexBuffer);
        s.indexBuffer = nullptr;
    }
    if (s.cameraEntity) {
        s.engine->destroyCameraComponent(s.cameraEntity);
        utils::EntityManager::get().destroy(s.cameraEntity);
        s.cameraEntity.clear();
        s.camera = nullptr;
    }
    if (s.view) {
        s.engine->destroy(s.view);
        s.view = nullptr;
    }
    if (s.scene) {
        s.engine->destroy(s.scene);
        s.scene = nullptr;
    }
    // Filament docs: destroy in reverse creation order —
    // view, scene, renderer, swapChain, engine last.
    if (s.renderer) {
        s.engine->destroy(s.renderer);
        s.renderer = nullptr;
    }
    if (s.swapChain) {
        s.engine->destroy(s.swapChain);
        s.swapChain = nullptr;
    }
    filament::Engine::destroy(s.engine);
    s.engine = nullptr;
    s.width = s.height = 0;
}

#endif // TILES_WITH_FILAMENT

bool g_initialized = false;

// P12: last failure description (see Renderer::lastError()). Only written
// on the render thread (the API is single-threaded), so no locking.
std::string g_lastError;

void setLastError(const std::string& message) {
    g_lastError = message;
    if (!message.empty()) {
        std::cerr << "[tiles_renderer] error: " << message << std::endl;
    }
}

} // namespace

bool Renderer::initialize(const RendererConfig& config) {
    if (config.window == nullptr || config.width == 0 || config.height == 0) {
        setLastError("initialize: invalid config "
                     "(need non-null window + nonzero width/height)");
        return false;
    }
    if (g_initialized) {
        setLastError("initialize: already initialized");
        return false;
    }
    setLastError("");

#ifdef TILES_WITH_FILAMENT
    // ---- Real Filament backend (P2 Linux, P4 other platforms) ----
    FilamentState& s = g_state;
    s.engine = filament::Engine::create(TILES_FILAMENT_BACKEND);
    if (s.engine == nullptr) {
        setLastError(std::string("initialize: Engine::create(") +
                     TILES_PLATFORM_NAME + ") failed");
        return false;
    }
    // Native window handle interpretation is platform-specific, but every
    // platform funnels through Engine::createSwapChain(void*):
    //   linux   : X11 Window / wl_surface* (void*)
    //   android : ANativeWindow* (NativeWindowHandle is already that type)
    //   windows : HWND (void*)
    //   ios     : UIView* (void*)
    void* nativeWindow = reinterpret_cast<void*>(config.window);
    s.swapChain = s.engine->createSwapChain(nativeWindow);
    if (s.swapChain == nullptr) {
        setLastError("initialize: createSwapChain failed");
        destroyFilamentState();
        return false;
    }
    s.nativeWindow = nativeWindow;
    s.width = config.width;
    s.height = config.height;

    s.renderer = s.engine->createRenderer();
    s.scene = s.engine->createScene();
    s.view = s.engine->createView();
    s.view->setScene(s.scene);
    s.view->setPostProcessingEnabled(false); // faster on software GL; P2 demo
    // P37: No MSAA. Per 2026-10-08 decision, no-AA is the correct comparison
    // method (MSAA implementations differ between SwiftShader/WebGL and
    // Filament, contributing ~0.5-0.9% systematic edge differences that mask
    // real rendering gaps). Both sides render without anti-aliasing.

    s.cameraEntity = utils::EntityManager::get().create();
    s.camera = s.engine->createCamera(s.cameraEntity);
    const double aspect =
        static_cast<double>(config.width) / static_cast<double>(config.height);
    // P37-C1: FOV configurable via setFovDegrees() (default 60, was 45).
    s.camera->setProjection(s.fovDegrees, aspect, s.nearPlane, s.farPlane);
    s.camera->lookAt({0.0, 0.0, 4.0}, {0.0, 0.0, 0.0}, {0.0, 1.0, 0.0});
    s.view->setCamera(s.camera);
    s.view->setViewport(
        filament::Viewport{0, 0, config.width, config.height});

    filament::Renderer::ClearOptions clearOptions;
    // P37-C1: configurable via setClearColor() (cesium.js conformance).
    clearOptions.clearColor = {s.clearColor[0], s.clearColor[1],
                               s.clearColor[2], s.clearColor[3]};
    clearOptions.clear = true;
    s.renderer->setClearOptions(clearOptions);

    // P3: a directional "sun" so PBR glTF tile content is lit. It does not
    // affect the P2 unlit triangle material.
    s.sunLight = utils::EntityManager::get().create();
    filament::LightManager::Builder(filament::LightManager::Type::DIRECTIONAL)
        .color({1.0f, 0.98f, 0.95f})
        .intensity(100000.0f)
        .direction({0.0f, -1.0f, 0.35f})
        .build(*s.engine, s.sunLight);
    s.scene->addEntity(s.sunLight);

    // P26: default procedural IBL (on unless the host calls
    // setIblEnabled(false)). A graceful fallback: if the environment can't
    // be built, the scene keeps sun-only lighting.
    {
        default_ibl::BuiltIbl ibl = default_ibl::build(*s.engine);
        if (ibl.light != nullptr) {
            s.ibl = ibl.light;
            s.iblReflections = ibl.reflections;
            s.scene->setIndirectLight(s.ibl);
            std::cout << "[tiles_renderer] IBL enabled (procedural environment)"
                      << std::endl;
        } else {
            std::cout << "[tiles_renderer] IBL unavailable; sun-only lighting"
                      << std::endl;
        }
    }

    // Triangle geometry.
    s.vertexBuffer =
        filament::VertexBuffer::Builder()
            .vertexCount(3)
            .bufferCount(1)
            .attribute(filament::VertexAttribute::POSITION, 0,
                       filament::VertexBuffer::AttributeType::FLOAT3, 0,
                       sizeof(filament::math::float3))
            .build(*s.engine);
    s.vertexBuffer->setBufferAt(
        *s.engine, 0,
        filament::VertexBuffer::BufferDescriptor(kTriangleVerts,
                                                 sizeof(kTriangleVerts)));
    s.indexBuffer = filament::IndexBuffer::Builder()
                        .indexCount(3)
                        .bufferType(filament::IndexBuffer::IndexType::USHORT)
                        .build(*s.engine);
    s.indexBuffer->setBuffer(
        *s.engine,
        filament::IndexBuffer::BufferDescriptor(kTriangleIndices,
                                                sizeof(kTriangleIndices)));

    s.material = filament::Material::Builder()
                     .package(unlit_color_filamat, unlit_color_filamat_len)
                     .build(*s.engine);
    s.materialInstance = s.material->createInstance();
    s.materialInstance->setParameter("color", filament::RgbType::LINEAR,
                                         filament::math::float3{1.0f, 0.0f,
                                                                0.0f}); // pure red

    s.renderable = utils::EntityManager::get().create();
    filament::RenderableManager::Builder(1)
        .boundingBox({{-1.0f, -1.0f, -1.0f}, {1.0f, 1.0f, 1.0f}})
        .material(0, s.materialInstance)
        .geometry(0, filament::RenderableManager::PrimitiveType::TRIANGLES,
                  s.vertexBuffer, s.indexBuffer, 0, 3)
        .culling(false)
        .receiveShadows(false)
        .castShadows(false)
        .build(*s.engine, s.renderable);
    // P3: the P2 triangle is only added to the scene by renderFrame() when no
    // tileset is loaded (keeps the P2 screenshot test pixel-identical).
    s.triangleInScene = false;

    std::cout << "[tiles_renderer] initialized " << config.width << "x"
              << config.height << " (SDK v" << TILES_RENDERER_VERSION << ", "
              << TILES_PLATFORM_NAME << ")" << std::endl;
    g_initialized = true;
    return true;
#else
    // P1 stub path (built without Filament): config validation only.
    std::cout << "[tiles_renderer] initialized " << config.width << "x"
              << config.height << " (SDK v" << TILES_RENDERER_VERSION
              << ", stub: Filament disabled)" << std::endl;
    g_initialized = true;
    return true;
#endif
}

bool Renderer::renderFrame() {
    if (!g_initialized) {
        return false;
    }
#ifdef TILES_WITH_FILAMENT
    FilamentState& s = g_state;
    if (s.engine == nullptr || s.renderer == nullptr || s.swapChain == nullptr) {
        return false;
    }
    // P3: when a tileset is loaded, drive the orbit camera and tile
    // selection/LOD every frame, and hide the P2 triangle.
    const bool useTileset = s.tileset != nullptr && s.tileset->isLoaded();
    if (useTileset) {
        // P37-C1: explicit lookAt camera overrides the orbit camera.
        if (s.explicitCam.enabled) {
            // P37-C1 fix: tiles are rendered rebased around the tileset's
            // local origin (world - localOrigin), so the explicit camera
            // (given in world space) must be rebased the same way.
            double origin[3] = {0.0, 0.0, 0.0};
            if (s.tileset) {
                s.tileset->localOrigin(origin);
            }
            // P37-FLOAT: Compute view matrix in DOUBLE on CPU.
            // modelView = view * model will be computed in double per tile,
            // small result uploaded to GPU. Shader never sees large matrices.
            double eyeD[3] = {
                s.explicitCam.eye[0] - origin[0],
                s.explicitCam.eye[1] - origin[1],
                s.explicitCam.eye[2] - origin[2]};
            double targetD[3] = {
                s.explicitCam.target[0] - origin[0],
                s.explicitCam.target[1] - origin[1],
                s.explicitCam.target[2] - origin[2]};
            double upD[3] = {s.explicitCam.up[0], s.explicitCam.up[1], s.explicitCam.up[2]};
            // Compute view matrix (lookAt) in double.
            double zaxis[3] = {eyeD[0]-targetD[0], eyeD[1]-targetD[1], eyeD[2]-targetD[2]};
            double zlen = std::sqrt(zaxis[0]*zaxis[0] + zaxis[1]*zaxis[1] + zaxis[2]*zaxis[2]);
            zaxis[0]/=zlen; zaxis[1]/=zlen; zaxis[2]/=zlen;
            double xaxis[3] = {
                upD[1]*zaxis[2] - upD[2]*zaxis[1],
                upD[2]*zaxis[0] - upD[0]*zaxis[2],
                upD[0]*zaxis[1] - upD[1]*zaxis[0]};
            double xlen = std::sqrt(xaxis[0]*xaxis[0] + xaxis[1]*xaxis[1] + xaxis[2]*xaxis[2]);
            xaxis[0]/=xlen; xaxis[1]/=xlen; xaxis[2]/=xlen;
            double yaxis[3] = {
                zaxis[1]*xaxis[2] - zaxis[2]*xaxis[1],
                zaxis[2]*xaxis[0] - zaxis[0]*xaxis[2],
                zaxis[0]*xaxis[1] - zaxis[1]*xaxis[0]};
            double viewD[16] = {
                xaxis[0], yaxis[0], zaxis[0], 0,
                xaxis[1], yaxis[1], zaxis[1], 0,
                xaxis[2], yaxis[2], zaxis[2], 0,
                -(xaxis[0]*eyeD[0] + xaxis[1]*eyeD[1] + xaxis[2]*eyeD[2]),
                -(yaxis[0]*eyeD[0] + yaxis[1]*eyeD[1] + yaxis[2]*eyeD[2]),
                -(zaxis[0]*eyeD[0] + zaxis[1]*eyeD[1] + zaxis[2]*eyeD[2]),
                1};
            if (s.tileset) {
                s.tileset->setViewMatrix(viewD);
            }
            // P37-FLOAT: Set Filament camera view to identity. The per-tile
            // modelView (view * model, computed in double) is uploaded as the
            // "model" matrix. Shader sees P * I * modelView * pos.
            const filament::math::mat4f identity;
            s.camera->setModelMatrix(identity);
            // Note: projection is set separately and remains valid.
        } else {
            constexpr float kDegToRad = 3.14159265358979323846f / 180.0f;
            const float yaw = s.orbit.yawDegrees * kDegToRad;
            const float pitch = s.orbit.pitchDegrees * kDegToRad;
            const float d = s.orbit.distance;
            // P5: tiles are rendered rebased around the tileset's local origin
            // (world - localOrigin, in double precision), so the Filament camera
            // always orbits (0,0,0) here. Tile *selection* still uses the true
            // world-space origin (see TilesetRenderer::update).
            const filament::math::float3 target{0.0f, 0.0f, 0.0f};
            const filament::math::float3 eye{
                target.x + d * std::cos(pitch) * std::sin(yaw),
                target.y + d * std::sin(pitch),
                target.z + d * std::cos(pitch) * std::cos(yaw)};
            s.camera->lookAt(eye, target, {0.0f, 1.0f, 0.0f});
        }
        // P36: debugFreezeFrame skips the tile selection/LOD update; the
        // last frame's tiles keep rendering (cesium.js debugFreezeFrame).
        if (!g_debugFreezeFrame) {
            // P37-C1: tile selection needs an OrbitCamera; synthesize one
            // from the explicit camera (eye-target vector -> yaw/pitch/dist).
            if (s.explicitCam.enabled) {
                OrbitCamera synth;
                synth.targetX = static_cast<float>(s.explicitCam.target[0]);
                synth.targetY = static_cast<float>(s.explicitCam.target[1]);
                synth.targetZ = static_cast<float>(s.explicitCam.target[2]);
                const double dx = s.explicitCam.eye[0] - s.explicitCam.target[0];
                const double dy = s.explicitCam.eye[1] - s.explicitCam.target[1];
                const double dz = s.explicitCam.eye[2] - s.explicitCam.target[2];
                const double d = std::sqrt(dx*dx + dy*dy + dz*dz);
                synth.distance = static_cast<float>(d);
                if (d > 1e-9) {
                    synth.pitchDegrees = static_cast<float>(
                        std::asin(dy / d) * 180.0 / 3.14159265358979323846);
                    synth.yawDegrees = static_cast<float>(
                        std::atan2(dx, dz) * 180.0 / 3.14159265358979323846);
                }
                s.tileset->update(s.width, s.height, synth);
            } else {
                s.tileset->update(s.width, s.height, s.orbit);
            }
        }
        if (s.triangleInScene) {
            s.scene->remove(s.renderable);
            s.triangleInScene = false;
        }
    } else if (!s.triangleInScene && s.renderable) {
        s.scene->addEntity(s.renderable);
        s.triangleInScene = true;
    }
    if (s.renderer->beginFrame(s.swapChain)) {
        s.renderer->render(s.view);
        // P36: dev-tool overlay (Inspector panel). Runs after the 3D view,
        // before present; the demo renders its own UI view here.
        if (g_overlayCallback) {
            g_overlayCallback();
        }
        s.renderer->endFrame();
        // Dispatch any pending driver callbacks (e.g. readPixels completion)
        // on this thread, once per frame as Filament recommends.
        s.engine->pumpMessageQueues();
        return true;
    }
    return false; // swap chain not ready (e.g. resized); caller may retry
#else
    return true; // stub path
#endif
}

bool Renderer::readPixels(std::vector<std::uint8_t>& outRgba,
                          std::uint32_t& outWidth, std::uint32_t& outHeight) {
    if (!g_initialized) {
        return false;
    }
#ifdef TILES_WITH_FILAMENT
    FilamentState& s = g_state;
    if (s.engine == nullptr || s.renderer == nullptr || s.swapChain == nullptr ||
        s.width == 0 || s.height == 0) {
        return false;
    }
    outWidth = s.width;
    outHeight = s.height;
    outRgba.assign(outWidth * outHeight * 4u, 0);

    // readPixels() must be issued inside a frame; its callback fires on the
    // main thread after a few more beginFrame/render/endFrame pumps.
    std::atomic<bool> done{false};
    auto onReadback = [](void* /*buffer*/, std::size_t /*size*/, void* user) {
        static_cast<std::atomic<bool>*>(user)->store(true);
    };
    bool issued = false;
    // beginFrame() is non-blocking and may return false if the driver is
    // still busy with the previous frame. Retry briefly before giving up.
    const auto beginDeadline =
        std::chrono::steady_clock::now() + std::chrono::seconds(5);
    while (!issued && std::chrono::steady_clock::now() < beginDeadline) {
        if (s.renderer->beginFrame(s.swapChain)) {
            issued = true;
            s.renderer->render(s.view);
            // P36: include the dev-tool overlay in screenshots too.
            if (g_overlayCallback) {
                g_overlayCallback();
            }
            s.renderer->readPixels(
                0, 0, outWidth, outHeight,
                filament::backend::PixelBufferDescriptor(
                    outRgba.data(), outRgba.size(),
                    filament::backend::PixelBufferDescriptor::PixelDataFormat::
                        RGBA,
                    filament::backend::PixelBufferDescriptor::PixelDataType::
                        UBYTE,
                    onReadback, &done));
            s.renderer->endFrame();
        } else {
            s.engine->pumpMessageQueues();
            std::this_thread::sleep_for(std::chrono::milliseconds(10));
        }
    }
    if (!issued) {
        std::cerr << "[tiles_renderer] readPixels: could not start a frame"
                  << std::endl;
        return false;
    }
    // Pump frames until the read-back callback fires (or we time out).
    // beginFrame() is non-blocking and returns false while the driver is
    // still busy (e.g. software GL), so pace the attempts like a main loop.
    // pumpMessageQueues() dispatches the readPixels completion callback on
    // this thread (Filament queues driver callbacks for the main thread).
    const auto deadline =
        std::chrono::steady_clock::now() + std::chrono::seconds(15);
    while (!done.load() && std::chrono::steady_clock::now() < deadline) {
        s.engine->pumpMessageQueues();
        if (done.load()) {
            break;
        }
        if (s.renderer->beginFrame(s.swapChain)) {
            s.renderer->render(s.view);
            s.renderer->endFrame();
        } else {
            std::this_thread::sleep_for(std::chrono::milliseconds(4));
        }
    }
    if (!done.load()) {
        std::cerr << "[tiles_renderer] readPixels: timed out waiting for "
                     "read-back" << std::endl;
        return false;
    }
    return true;
#else
    (void)outRgba;
    (void)outWidth;
    (void)outHeight;
    return false; // stub path: nothing rendered
#endif
}

void Renderer::shutdown() {
#ifdef TILES_WITH_FILAMENT
    // P3: destroy the tileset first — tile teardown calls free(), which
    // needs a live Filament engine/scene.
    g_state.tileset.reset();
    destroyFilamentState();
#endif
    g_initialized = false;
    std::cout << "[tiles_renderer] shutdown" << std::endl;
}

bool Renderer::loadTileset(const std::string& tilesetUrl) {
    return loadTileset(tilesetUrl, TilesetOptions{});
}

bool Renderer::loadTileset(const std::string& tilesetUrl,
                           const TilesetOptions& options) {
    if (!g_initialized) {
        setLastError("loadTileset: not initialized");
        return false;
    }
    setLastError("");
#ifdef TILES_WITH_FILAMENT
    FilamentState& s = g_state;
    if (s.engine == nullptr || s.scene == nullptr) {
        setLastError("loadTileset: engine not ready");
        return false;
    }
    auto tileset = std::make_unique<TilesetRenderer>(s.engine, s.scene);
    // P19: apply a budget set before load (no-op when never set).
    tileset->setMaxCachedBytes(g_pendingMaxCachedBytes);
    // P31: apply a pending live SSE override (no-op when never set).
    if (g_hasPendingMaxSse) {
        tileset->setMaximumScreenSpaceError(g_pendingMaxSse);
    }
    // P32: event callbacks persist across loads; the new TilesetRenderer
    // gets the current set before loading.
    tileset->setEventCallbacks(g_eventCallbacks);
    // P33: show / preloadWhenHidden / modelMatrix persist across loads;
    // the new TilesetRenderer gets the current values before loading.
    tileset->setShow(g_show);
    tileset->setPreloadWhenHidden(g_preloadWhenHidden);
    tileset->setModelMatrix(g_modelMatrix);
    tileset->setEnableShowOutline(g_enableShowOutline);
    tileset->setShowOutline(g_showOutline);
    tileset->setOutlineColor(
        g_outlineColor[0], g_outlineColor[1], g_outlineColor[2]);
    tileset->setDebugShowBoundingVolume(g_debugShowBoundingVolume);
    tileset->setDebugShowContentBoundingVolume(
        g_debugShowContentBoundingVolume);
    tileset->setDebugShowViewerRequestVolume(
        g_debugShowViewerRequestVolume);
    tileset->setDebugFreezeFrame(g_debugFreezeFrame);
    tileset->setDebugShowUrl(g_debugShowUrl);
    // P22: build-then-commit. The new TilesetRenderer is fully loaded
    // before it replaces the old one, so a failed loadTileset() (bad
    // path, corrupt tileset.json, timeout) leaves the currently-loaded
    // tileset untouched and rendering. The old code reset s.tileset up
    // front, destroying the working tileset even when the new load failed.
    if (!tileset->load(tilesetUrl, options)) {
        setLastError("loadTileset: " + tileset->lastError());
        return false;
    }
    // P32: the old tileset's content is released by the replacement below;
    // fire tileUnload for its loaded tiles first (synchronously, on the
    // render thread). Only on success — a failed load leaves the old
    // tileset untouched, so no unload events.
    if (s.tileset) {
        s.tileset->fireTileUnloadEvents();
    }
    s.tileset.reset(); // drop the previous tileset only on success
    s.tileset = std::move(tileset);
    return true;
#else
    (void)tilesetUrl;
    setLastError("loadTileset: not available in this build");
    return false;
#endif
}

bool Renderer::resize(std::uint32_t width, std::uint32_t height) {
    if (!g_initialized) {
        setLastError("resize: not initialized");
        return false;
    }
    if (width == 0 || height == 0) {
        setLastError("resize: dimensions must be nonzero");
        return false;
    }
    setLastError("");
#ifdef TILES_WITH_FILAMENT
    FilamentState& s = g_state;
    if (s.engine == nullptr || s.swapChain == nullptr ||
        s.nativeWindow == nullptr) {
        setLastError("resize: engine not ready");
        return false;
    }
    if (width == s.width && height == s.height) {
        return true; // no-op
    }
    // Recreate the swap chain for the same native window (the host owns the
    // window and is responsible for resizing the OS-level surface first).
    // Called between frames on the render thread, so no in-flight frame is
    // using the old swap chain.
    s.engine->destroy(s.swapChain);
    s.swapChain = s.engine->createSwapChain(s.nativeWindow);
    if (s.swapChain == nullptr) {
        setLastError("resize: createSwapChain failed");
        return false;
    }
    s.width = width;
    s.height = height;
    s.view->setViewport(filament::Viewport{0, 0, width, height});
    const double aspect = static_cast<double>(width) / static_cast<double>(height);
    // P37-C1: use saved FOV (not hardcoded 45°) so setFovDegrees() survives resize.
    s.camera->setProjection(s.fovDegrees, aspect, s.nearPlane, s.farPlane);
    std::cout << "[tiles_renderer] resized to " << width << "x" << height
              << std::endl;
    return true;
#else
    return true; // stub path: nothing to resize
#endif
}

std::string Renderer::lastError() {
    return g_lastError;
}

void Renderer::setOrbitCamera(
    float yawDegrees, float pitchDegrees, float distance) {
    if (!g_initialized) {
        return;
    }
#ifdef TILES_WITH_FILAMENT
    g_state.orbit.yawDegrees = yawDegrees;
    g_state.orbit.pitchDegrees = pitchDegrees;
    g_state.orbit.distance = distance;
#else
    (void)yawDegrees;
    (void)pitchDegrees;
    (void)distance;
#endif
}

// P37-C1: explicit lookAt camera.
void Renderer::setCamera(const double eye[3], const double target[3],
                         const double up[3]) {
    if (!g_initialized) {
        return;
    }
    for (int i = 0; i < 3; ++i) {
        g_state.explicitCam.eye[i] = eye[i];
        g_state.explicitCam.target[i] = target[i];
        g_state.explicitCam.up[i] = up[i];
    }
    g_state.explicitCam.enabled = true;
}

void Renderer::clearExplicitCamera() {
    if (!g_initialized) {
        return;
    }
    g_state.explicitCam.enabled = false;
}

bool Renderer::hasExplicitCamera() {
    if (!g_initialized) {
        return false;
    }
    return g_state.explicitCam.enabled;
}

// P37-C1: clear color and FOV.
void Renderer::setClearColor(float r, float g, float b, float a) {
    if (!g_initialized) {
        return;
    }
    g_state.clearColor[0] = r;
    g_state.clearColor[1] = g;
    g_state.clearColor[2] = b;
    g_state.clearColor[3] = a;
#ifdef TILES_WITH_FILAMENT
    if (g_state.renderer) {
        filament::Renderer::ClearOptions clearOptions;
        clearOptions.clearColor = {r, g, b, a};
        clearOptions.clear = true;
        g_state.renderer->setClearOptions(clearOptions);
    }
#endif
}

void Renderer::setFovDegrees(float fovDegrees) {
    if (!g_initialized) {
        return;
    }
    g_state.fovDegrees = fovDegrees;
#ifdef TILES_WITH_FILAMENT
    if (g_state.camera) {
        const double aspect = static_cast<double>(g_state.width) /
                              static_cast<double>(g_state.height);
        g_state.camera->setProjection(fovDegrees, aspect,
                                      g_state.nearPlane, g_state.farPlane);
    }
#endif
}

void Renderer::setClipPlanes(double nearPlane, double farPlane) {
    if (!g_initialized) {
        return;
    }
    g_state.nearPlane = nearPlane;
    g_state.farPlane = farPlane;
#ifdef TILES_WITH_FILAMENT
    if (g_state.camera) {
        const double aspect = static_cast<double>(g_state.width) /
                              static_cast<double>(g_state.height);
        g_state.camera->setProjection(g_state.fovDegrees, aspect,
                                      nearPlane, farPlane);
    }
#endif
}

int Renderer::renderedTileCount() {
    if (!g_initialized) {
        return -1;
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset == nullptr) {
        return -1;
    }
    return g_state.tileset->renderedTileCount();
#else
    return -1;
#endif
}

Renderer::TileStats Renderer::tileStats() {
    if (!g_initialized) {
        return TileStats{}; // all -1
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset == nullptr) {
        return TileStats{}; // all -1
    }
    return g_state.tileset->tileStats();
#else
    return TileStats{};
#endif
}

std::vector<std::string> Renderer::selectedTileIds() {
    if (!g_initialized) {
        return {};
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset == nullptr) {
        return {};
    }
    return g_state.tileset->selectedTileIds();
#else
    return {};
#endif
}

const char* Renderer::version() {
    return TILES_RENDERER_VERSION;
}

void Renderer::setMaxCachedBytes(std::int64_t bytes) {
    if (!g_initialized) {
        return;
    }
    // Stash: applies to the next loadTileset() even when no tileset is
    // loaded yet. Forward live when one is.
    g_pendingMaxCachedBytes = bytes;
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->setMaxCachedBytes(bytes);
    }
#endif
}

// P31: live LOD screen-space error budget. Same stash-then-forward pattern
// as setMaxCachedBytes: applies to the next loadTileset() when no tileset
// is loaded, and takes effect on the next frame when one is. Values < 0
// (or NaN) restore the default of 16 — normalized at stash time so the
// pre-load and live paths agree.
void Renderer::setMaximumScreenSpaceError(double sse) {
    if (!g_initialized) {
        return;
    }
    g_hasPendingMaxSse = true;
    g_pendingMaxSse = sse >= 0.0 ? sse : 16.0;
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->setMaximumScreenSpaceError(g_pendingMaxSse);
    }
#endif
}

double Renderer::maximumScreenSpaceError() {
    if (!g_initialized) {
        return 16.0;
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        return g_state.tileset->maximumScreenSpaceError();
    }
#endif
    return g_hasPendingMaxSse ? g_pendingMaxSse : 16.0;
}

Renderer::TilesetOptions Renderer::currentTilesetOptions() {
#ifdef TILES_WITH_FILAMENT
    if (g_initialized && g_state.tileset != nullptr) {
        return g_state.tileset->currentOptions();
    }
#endif
    return TilesetOptions{};
}

// P32: register event callbacks. Stored in g_eventCallbacks (survives
// loadTileset) and forwarded to the live TilesetRenderer when one exists.
void Renderer::setEventCallbacks(const TilesetEventCallbacks& callbacks) {
    if (!g_initialized) {
        return;
    }
    g_eventCallbacks = callbacks;
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->setEventCallbacks(callbacks);
    }
#endif
}

void Renderer::clearEventCallbacks() {
    if (!g_initialized) {
        return;
    }
    g_eventCallbacks = TilesetEventCallbacks{};
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->setEventCallbacks(g_eventCallbacks);
    }
#endif
}

// P33: show / preloadWhenHidden / modelMatrix (see renderer.h). Stored in
// the g_* stash (persist across loadTileset) and forwarded to the live
// TilesetRenderer when one exists; each new TilesetRenderer gets the
// stash at load.
void Renderer::setShow(bool show) {
    if (!g_initialized) {
        return;
    }
    g_show = show;
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->setShow(show);
    }
#endif
}

bool Renderer::isShow() {
    if (!g_initialized) {
        return true;
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        return g_state.tileset->isShow();
    }
#endif
    return g_show;
}

void Renderer::setEnableShowOutline(bool enable) {
    if (!g_initialized) {
        return;
    }
    g_enableShowOutline = enable;
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->setEnableShowOutline(enable);
    }
#endif
}

bool Renderer::isEnableShowOutline() {
    if (!g_initialized) {
        return true;
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        return g_state.tileset->isEnableShowOutline();
    }
#endif
    return g_enableShowOutline;
}

void Renderer::setShowOutline(bool show) {
    if (!g_initialized) {
        return;
    }
    g_showOutline = show;
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->setShowOutline(show);
    }
#endif
}

bool Renderer::isShowOutline() {
    if (!g_initialized) {
        return true;
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        return g_state.tileset->isShowOutline();
    }
#endif
    return g_showOutline;
}

void Renderer::setOutlineColor(float r, float g, float b) {
    if (!g_initialized) {
        return;
    }
    g_outlineColor[0] = r;
    g_outlineColor[1] = g;
    g_outlineColor[2] = b;
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->setOutlineColor(r, g, b);
    }
#endif
}

void Renderer::outlineColor(float out[3]) {
    if (!g_initialized) {
        out[0] = out[1] = out[2] = 0.0f;
        return;
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->outlineColor(out);
        return;
    }
#endif
    out[0] = g_outlineColor[0];
    out[1] = g_outlineColor[1];
    out[2] = g_outlineColor[2];
}

void Renderer::setPreloadWhenHidden(bool preload) {
    if (!g_initialized) {
        return;
    }
    g_preloadWhenHidden = preload;
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->setPreloadWhenHidden(preload);
    }
#endif
}

bool Renderer::isPreloadWhenHidden() {
    if (!g_initialized) {
        return false;
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        return g_state.tileset->isPreloadWhenHidden();
    }
#endif
    return g_preloadWhenHidden;
}

void Renderer::setModelMatrix(const double matrix[16]) {
    if (!g_initialized) {
        return;
    }
    for (int i = 0; i < 16; ++i) {
        g_modelMatrix[i] = matrix[i];
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->setModelMatrix(matrix);
    }
#endif
}

void Renderer::modelMatrix(double out[16]) {
    double* src = g_modelMatrix;
#ifdef TILES_WITH_FILAMENT
    double live[16];
    if (g_initialized && g_state.tileset != nullptr) {
        g_state.tileset->modelMatrix(live);
        src = live;
    }
#endif
    for (int i = 0; i < 16; ++i) {
        out[i] = src[i];
    }
}

bool Renderer::tilesLoaded() {
#ifdef TILES_WITH_FILAMENT
    if (g_initialized && g_state.tileset != nullptr) {
        return g_state.tileset->tilesLoaded();
    }
#endif
    return false;
}

Renderer::BoundingSphere Renderer::boundingSphere() {
    Renderer::BoundingSphere out{{0.0, 0.0, 0.0}, 0.0};
#ifdef TILES_WITH_FILAMENT
    if (g_initialized && g_state.tileset != nullptr) {
        return g_state.tileset->boundingSphere();
    }
#endif
    return out;
}

std::int64_t Renderer::timeSinceLoadMs() {
#ifdef TILES_WITH_FILAMENT
    if (g_initialized && g_state.tileset != nullptr) {
        return g_state.tileset->timeSinceLoadMs();
    }
#endif
    return 0;
}

std::string Renderer::rootTileId() {
#ifdef TILES_WITH_FILAMENT
    if (g_initialized && g_state.tileset != nullptr) {
        return g_state.tileset->rootTileId();
    }
#endif
    return "";
}

// P34: cache / statistics. Pure live queries (no stash needed — they
// only make sense against a loaded tileset).
std::int64_t Renderer::totalMemoryUsageInBytes() {
#ifdef TILES_WITH_FILAMENT
    if (g_initialized && g_state.tileset != nullptr) {
        return g_state.tileset->totalMemoryUsageInBytes();
    }
#endif
    return 0;
}

void Renderer::trimLoadedTiles() {
#ifdef TILES_WITH_FILAMENT
    if (g_initialized && g_state.tileset != nullptr) {
        g_state.tileset->trimLoadedTiles();
    }
#endif
}

bool Renderer::hasExtension(const std::string& name) {
#ifdef TILES_WITH_FILAMENT
    if (g_initialized && g_state.tileset != nullptr) {
        return g_state.tileset->hasExtension(name);
    }
#endif
    (void)name;
    return false;
}

// P35: debug switches (see renderer.h). P36: split volume flags + freeze
// frame. Stash-then-forward across loadTileset(), same pattern as the P33
// display flags.
void Renderer::setDebugShowBoundingVolume(bool show) {
    if (!g_initialized) {
        return;
    }
    g_debugShowBoundingVolume = show;
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->setDebugShowBoundingVolume(show);
    }
#endif
}

bool Renderer::isDebugShowBoundingVolume() {
    return g_debugShowBoundingVolume;
}

void Renderer::setDebugShowContentBoundingVolume(bool show) {
    if (!g_initialized) {
        return;
    }
    g_debugShowContentBoundingVolume = show;
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->setDebugShowContentBoundingVolume(show);
    }
#endif
}

bool Renderer::isDebugShowContentBoundingVolume() {
    return g_debugShowContentBoundingVolume;
}

void Renderer::setDebugShowViewerRequestVolume(bool show) {
    if (!g_initialized) {
        return;
    }
    g_debugShowViewerRequestVolume = show;
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->setDebugShowViewerRequestVolume(show);
    }
#endif
}

bool Renderer::isDebugShowViewerRequestVolume() {
    return g_debugShowViewerRequestVolume;
}

void Renderer::setDebugFreezeFrame(bool freeze) {
    if (!g_initialized) {
        return;
    }
    g_debugFreezeFrame = freeze;
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->setDebugFreezeFrame(freeze);
    }
#endif
}

bool Renderer::isDebugFreezeFrame() {
    return g_debugFreezeFrame;
}

void Renderer::setOverlayCallback(OverlayCallback cb) {
    g_overlayCallback = std::move(cb);
}

void* Renderer::nativeEngineHandle() {
#ifdef TILES_WITH_FILAMENT
    if (!g_initialized) {
        return nullptr;
    }
    return static_cast<void*>(g_state.engine);
#else
    return nullptr;
#endif
}

void* Renderer::nativeRendererHandle() {
#ifdef TILES_WITH_FILAMENT
    if (!g_initialized) {
        return nullptr;
    }
    return static_cast<void*>(g_state.renderer);
#else
    return nullptr;
#endif
}

void Renderer::setDebugShowUrl(bool show) {
    if (!g_initialized) {
        return;
    }
    g_debugShowUrl = show;
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->setDebugShowUrl(show);
    }
#endif
}

bool Renderer::isDebugShowUrl() {
    return g_debugShowUrl;
}

// P26: toggle the default procedural IBL. Cheap: only attaches/detaches the
// IndirectLight built once at initialize(); the cubemap and SH survive the
// session. No-op when IBL failed to build (sun-only fallback).
void Renderer::setIblEnabled(bool enabled) {
    if (!g_initialized) {
        return;
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.ibl == nullptr || g_state.scene == nullptr) {
        return;
    }
    if (g_state.iblEnabled == enabled) {
        return;
    }
    g_state.iblEnabled = enabled;
    g_state.scene->setIndirectLight(enabled ? g_state.ibl : nullptr);
    std::cout << "[tiles_renderer] IBL " << (enabled ? "enabled" : "disabled")
              << std::endl;
#else
    (void)enabled;
#endif
}

} // namespace tiles_renderer
