// tiles_renderer SDK implementation.
//
// P2: real Filament rendering on Linux (OpenGL backend, native X11/Wayland
// window handle). P4: the same engine/scene/view code now runs on Android
// (Vulkan + ANativeWindow), Windows (Vulkan + HWND), iOS (Metal + UIView)
// and Web (WebGL + canvas selector) — only the backend enum and the native
// handle interpretation differ per platform (see TILES_FILAMENT_BACKEND).

#include "tiles_renderer/renderer.h"

#include "tiles_renderer/version.h"
#include "tileset_internal.h"

#include <atomic>
#include <chrono>
#include <iostream>
#include <memory>
#include <thread>

#ifdef TILES_WITH_FILAMENT
#include <backend/PixelBufferDescriptor.h>
#include <filament/Camera.h>
#include <filament/Engine.h>
#include <filament/IndexBuffer.h>
#include <filament/IndirectLight.h>
#include <filament/LightManager.h>
#include <filament/Material.h>
#include <filament/RenderableManager.h>
#include <filament/Renderer.h>
#include <filament/Scene.h>
#include <filament/SwapChain.h>
#include <filament/Texture.h>
#include <filament/VertexBuffer.h>
#include <filament/View.h>
#include <filament/Viewport.h>
#include <utils/EntityManager.h>

#include <cmath>
#include <vector>

#include "unlit_color_filamat.h" // generated by cmake/embed_filamat.py (matc)
#endif

// P4: platform backend selection. TILES_PLATFORM_* is defined by CMake from
// the TILES_PLATFORM cache variable, so the choice follows the *target*
// platform rather than host compiler macros (matters for cross builds).
//
// Backend choice follows what each official Filament prebuilt ships:
//   linux   : OpenGL (X11 Window / wl_surface* as void*)
//   android : Vulkan (ANativeWindow*; android prebuilt ships bluevk only)
//   windows : Vulkan (HWND)
//   ios     : Metal (UIView*)
//   wasm    : default backend (WebGL); nativeWindow is the canvas CSS
//             selector string, used opaquely (see Filament jsbindings
//             _createSwapChainForCanvas)
#ifdef TILES_WITH_FILAMENT
#if defined(TILES_PLATFORM_ANDROID)
#define TILES_FILAMENT_BACKEND filament::Engine::Backend::VULKAN
#define TILES_PLATFORM_NAME "Android/Vulkan"
#elif defined(TILES_PLATFORM_WINDOWS)
#define TILES_FILAMENT_BACKEND filament::Engine::Backend::VULKAN
#define TILES_PLATFORM_NAME "Windows/Vulkan"
#elif defined(TILES_PLATFORM_IOS)
#define TILES_FILAMENT_BACKEND filament::Engine::Backend::METAL
#define TILES_PLATFORM_NAME "iOS/Metal"
#elif defined(TILES_PLATFORM_WASM)
#define TILES_FILAMENT_BACKEND filament::Engine::Backend::DEFAULT
#define TILES_PLATFORM_NAME "Web/WebGL"
#elif defined(TILES_PLATFORM_LINUX)
#define TILES_FILAMENT_BACKEND filament::Engine::Backend::OPENGL
#define TILES_PLATFORM_NAME "Linux/OpenGL"
#else
#error "TILES_PLATFORM_*: unknown target platform (expected CMake to define one)"
#endif
#endif // TILES_WITH_FILAMENT

namespace tiles_renderer {
namespace {

// P19: cache budget set before any tileset is loaded is stashed here and
// applied in loadTileset() before the cesium Tileset is constructed.
// P22-hotfix: this is a plain std::int64_t with no Filament dependency, so
// it lives OUTSIDE the TILES_WITH_FILAMENT guard — setMaxCachedBytes()
// references it unconditionally, and the WASM stub build (Filament OFF)
// failed with "use of undeclared identifier" (P22 CI).
std::int64_t g_pendingMaxCachedBytes = -1;

#ifdef TILES_WITH_FILAMENT

// P2 demo geometry: a single triangle. Static storage so the Filament buffer
// descriptors never dangle.
constexpr filament::math::float3 kTriangleVerts[3] = {
    {-0.6f, -0.5f, 0.0f},
    {0.6f, -0.5f, 0.0f},
    {0.0f, 0.6f, 0.0f},
};
constexpr std::uint16_t kTriangleIndices[3] = {0, 1, 2};

// ---------------------------------------------------------------------------
// P26: default image-based lighting.
//
// Before P26 the scene's only light was the P3 directional sun, so metals
// could only show the sun's specular lobe and were otherwise black
// (ADR-0013). We now add a Filament IndirectLight driven by a small
// *procedural* environment, generated deterministically at initialize():
//
// - 6 cubemap faces (64x64 RGBA8) from an analytic sky-gradient + sun
//   function; mipmaps generated on the GPU via Texture::generateMipmaps.
//   These feed the specular (reflections) part. Note: plain box-filtered
//   mips, not cmgen-quality GGX prefiltering — plausible for a default
//   outdoor environment; the tradeoff is documented in ADR-0025.
// - Diffuse irradiance as 3-band spherical harmonics of the same analytic
//   function (deterministic Fibonacci-sphere quadrature), passed via
//   IndirectLight::Builder::radiance(), which does the irradiance
//   convolution/scaling internally.
//
// Why procedural instead of an embedded .ktx: zero new dependencies, zero
// binary blobs, identical on every platform (pure Filament core API), and
// bit-deterministic. The sun blob sits at the direction *toward* the sun,
// matching the P3 directional light (whose .direction() is the direction
// light travels).
// ---------------------------------------------------------------------------
namespace default_ibl {

using filament::math::float3;

// 64x64 per face: 96KB total, generated once at initialize().
constexpr std::uint32_t kFaceSize = 64;

// Direction *toward* the procedural sun: normalize(-(0,-1,0.35)), the
// opposite of the P3 directional light's travel direction.
inline float3 sunDirection() {
    float3 d{0.0f, 1.0f, -0.35f};
    return d / length(d);
}

// Analytic outdoor environment (linear-space radiance, y-up). Deterministic:
// pure function of direction, no RNG, no tables.
float3 envRadiance(const float3& d) {
    const float sunDot = std::max(dot(d, sunDirection()), 0.0f);
    const float up = std::min(std::max(d.y, 0.0f), 1.0f);
    const float down = std::min(std::max(-d.y, 0.0f), 1.0f);
    // Sky: horizon -> zenith gradient; ground: dark.
    const float3 horizon{0.40f, 0.50f, 0.70f};
    const float3 zenith{0.09f, 0.15f, 0.34f};
    const float3 ground{0.08f, 0.075f, 0.07f};
    const float su = up * up * (3.0f - 2.0f * up); // smoothstep
    const float sd = down * down * (3.0f - 2.0f * down);
    const float3 base = d.y >= 0.0f ? horizon + (zenith - horizon) * su
                                    : horizon + (ground - horizon) * sd;
    // Sun disc + glow. Values above 1.0 clip on the RGBA8 upload; the disc
    // stays the brightest feature, which is what matters for reflections.
    const float disc =
        std::min(std::max((sunDot - 0.9993f) / 0.0004f, 0.0f), 1.0f);
    const float glow =
        std::pow(sunDot, 700.0f) * 0.55f + std::pow(sunDot, 24.0f) * 0.10f;
    return base + float3{1.0f, 0.97f, 0.90f} * (disc * 0.9f + glow);
}

// Cubemap face order used by Filament (see filament::FaceOffsets in the
// filament-generatePrefilterMipmap headers): +X, -X, +Y, -Y, +Z, -Z.
// Direction per face follows the OpenGL cubemap convention; (u, v) are the
// texel's normalized coordinates in [-1, 1], v = -1 at the first buffer row.
float3 faceDirection(int face, float u, float v) {
    const float s = u, t = v;
    float3 d{0.0f, 0.0f, 0.0f};
    switch (face) {
        case 0: d = float3{1.0f, -t, -s}; break;  // +X
        case 1: d = float3{-1.0f, -t, s}; break;  // -X
        case 2: d = float3{s, 1.0f, t}; break;    // +Y
        case 3: d = float3{s, -1.0f, -t}; break;  // -Y
        case 4: d = float3{s, -t, 1.0f}; break;   // +Z
        default: d = float3{-s, -t, -1.0f}; break; // -Z
    }
    return d / length(d);
}

// Real spherical-harmonics basis, graphics convention (no Condon-Shortley
// phase), index(l, m) = l * (l + 1) + m as documented in IndirectLight.h.
void shBasis(const float3& d, float* b /*[9]*/) {
    const float x = d.x, y = d.y, z = d.z;
    b[0] = 0.282095f;
    b[1] = 0.488603f * y;
    b[2] = 0.488603f * z;
    b[3] = 0.488603f * x;
    b[4] = 1.092548f * x * y;
    b[5] = 1.092548f * y * z;
    b[6] = 0.315392f * (3.0f * z * z - 1.0f);
    b[7] = 1.092548f * x * z;
    b[8] = 0.546274f * (x * x - y * y);
}

// Project envRadiance() onto 3 SH bands by deterministic Fibonacci-sphere
// quadrature. Returns *radiance* coefficients for
// IndirectLight::Builder::radiance().
void computeRadianceSH(float3* sh /*[9]*/) {
    constexpr int kSamples = 2048;
    constexpr float kPi = 3.14159265358979323846f;
    constexpr float kGolden = kPi * (3.0f - std::sqrt(5.0f));
    for (int k = 0; k < 9; ++k) {
        sh[k] = float3{0.0f, 0.0f, 0.0f};
    }
    for (int i = 0; i < kSamples; ++i) {
        const float z = 1.0f - 2.0f * (i + 0.5f) / kSamples;
        const float r = std::sqrt(std::max(0.0f, 1.0f - z * z));
        const float phi = kGolden * i;
        const float3 d{r * std::cos(phi), z, r * std::sin(phi)};
        const float3 L = envRadiance(d);
        float b[9];
        shBasis(d, b);
        for (int k = 0; k < 9; ++k) {
            sh[k] += L * b[k];
        }
    }
    const float scale = 4.0f * kPi / kSamples;
    for (int k = 0; k < 9; ++k) {
        sh[k] *= scale;
    }
}

struct BuiltIbl {
    filament::IndirectLight* light = nullptr;
    filament::Texture* reflections = nullptr;
};

// Build the default procedural IBL. Any failure returns {nullptr, nullptr}
// and the caller keeps sun-only lighting.
BuiltIbl build(filament::Engine& engine) {
    BuiltIbl out;
    filament::Texture* tex = filament::Texture::Builder()
                                 .width(kFaceSize)
                                 .height(kFaceSize)
                                 .levels(0xff)
                                 .usage(filament::Texture::Usage::DEFAULT |
                                        filament::Texture::Usage::GEN_MIPMAPPABLE)
                                 .format(filament::Texture::InternalFormat::RGBA8)
                                 .sampler(filament::Texture::Sampler::SAMPLER_CUBEMAP)
                                 .build(engine);
    if (tex == nullptr) {
        return out;
    }
    for (int face = 0; face < 6; ++face) {
        auto* px = new std::uint8_t[kFaceSize * kFaceSize * 4];
        for (std::uint32_t y = 0; y < kFaceSize; ++y) {
            for (std::uint32_t x = 0; x < kFaceSize; ++x) {
                const float u = 2.0f * (x + 0.5f) / kFaceSize - 1.0f;
                const float v = 2.0f * (y + 0.5f) / kFaceSize - 1.0f;
                const float3 L = envRadiance(faceDirection(face, u, v));
                std::uint8_t* p = px + (y * kFaceSize + x) * 4;
                p[0] = (std::uint8_t)(std::min(std::max(L.x, 0.0f), 1.0f) * 255.0f + 0.5f);
                p[1] = (std::uint8_t)(std::min(std::max(L.y, 0.0f), 1.0f) * 255.0f + 0.5f);
                p[2] = (std::uint8_t)(std::min(std::max(L.z, 0.0f), 1.0f) * 255.0f + 0.5f);
                p[3] = 255;
            }
        }
        filament::Texture::PixelBufferDescriptor pbd(
            px, kFaceSize * kFaceSize * 4, filament::Texture::Format::RGBA,
            filament::Texture::Type::UBYTE,
            [](void* buf, size_t, void*) { delete[] static_cast<std::uint8_t*>(buf); });
        // Cubemap faces are selected by zoffset: 0=+X .. 5=-Z.
        tex->setImage(engine, 0, 0, 0, (std::uint32_t)face, kFaceSize,
                      kFaceSize, 1, std::move(pbd));
    }
    tex->generateMipmaps(engine);

    float3 sh[9];
    computeRadianceSH(sh);
    out.light = filament::IndirectLight::Builder()
                    .reflections(tex)
                    .radiance(3, sh)
                    .intensity(30000.0f) // Filament default; env is 0..1 LDR
                    .build(engine);
    if (out.light == nullptr) {
        engine.destroy(tex);
        return out;
    }
    out.reflections = tex;
    return out;
}

} // namespace default_ibl

struct FilamentState {
    filament::Engine* engine = nullptr;
    filament::SwapChain* swapChain = nullptr;
    filament::Renderer* renderer = nullptr; // filament::Renderer (not this SDK class)
    filament::Scene* scene = nullptr;
    filament::View* view = nullptr;
    filament::Camera* camera = nullptr;
    utils::Entity cameraEntity{};
    utils::Entity renderable{};
    filament::VertexBuffer* vertexBuffer = nullptr;
    filament::IndexBuffer* indexBuffer = nullptr;
    filament::Material* material = nullptr;
    filament::MaterialInstance* materialInstance = nullptr;
    std::uint32_t width = 0;
    std::uint32_t height = 0;
    // P12: the native window handle passed to initialize(), kept so resize()
    // can recreate the swap chain for the same window. For WASM this points
    // at the host's canvas-selector string (host must keep it alive — same
    // rule as in initialize()).
    void* nativeWindow = nullptr;
    // P3: optional tileset integration (null when no tileset loaded).
    std::unique_ptr<TilesetRenderer> tileset;
    OrbitCamera orbit;
    utils::Entity sunLight{};
    // P26: default procedural IBL (IndirectLight + reflections cubemap).
    // Built once at initialize(); setIblEnabled() only toggles scene
    // membership, so the objects stay alive for the session.
    filament::IndirectLight* ibl = nullptr;
    filament::Texture* iblReflections = nullptr;
    bool iblEnabled = true;
    bool triangleInScene = false;
};

FilamentState g_state;

void destroyFilamentState() {
    FilamentState& s = g_state;
    if (s.engine == nullptr) {
        return;
    }
    // Destroy user resources first, engine last (Filament requirement).
    if (s.sunLight) {
        s.scene->remove(s.sunLight);
        s.engine->destroy(s.sunLight);
        utils::EntityManager::get().destroy(s.sunLight);
        s.sunLight.clear();
    }
    // P26: IBL must leave the scene before its objects are destroyed.
    if (s.ibl) {
        s.scene->setIndirectLight(nullptr);
        s.engine->destroy(s.ibl);
        s.ibl = nullptr;
    }
    if (s.iblReflections) {
        s.engine->destroy(s.iblReflections);
        s.iblReflections = nullptr;
    }
    s.iblEnabled = true;
    if (s.renderable) {
        if (s.triangleInScene) {
            s.scene->remove(s.renderable);
            s.triangleInScene = false;
        }
        s.engine->destroy(s.renderable);
        utils::EntityManager::get().destroy(s.renderable);
        s.renderable.clear();
    }
    if (s.materialInstance) {
        s.engine->destroy(s.materialInstance);
        s.materialInstance = nullptr;
    }
    if (s.material) {
        s.engine->destroy(s.material);
        s.material = nullptr;
    }
    if (s.vertexBuffer) {
        s.engine->destroy(s.vertexBuffer);
        s.vertexBuffer = nullptr;
    }
    if (s.indexBuffer) {
        s.engine->destroy(s.indexBuffer);
        s.indexBuffer = nullptr;
    }
    if (s.cameraEntity) {
        s.engine->destroyCameraComponent(s.cameraEntity);
        utils::EntityManager::get().destroy(s.cameraEntity);
        s.cameraEntity.clear();
        s.camera = nullptr;
    }
    if (s.view) {
        s.engine->destroy(s.view);
        s.view = nullptr;
    }
    if (s.scene) {
        s.engine->destroy(s.scene);
        s.scene = nullptr;
    }
    // Filament docs: destroy in reverse creation order —
    // view, scene, renderer, swapChain, engine last.
    if (s.renderer) {
        s.engine->destroy(s.renderer);
        s.renderer = nullptr;
    }
    if (s.swapChain) {
        s.engine->destroy(s.swapChain);
        s.swapChain = nullptr;
    }
    filament::Engine::destroy(s.engine);
    s.engine = nullptr;
    s.width = s.height = 0;
}

#endif // TILES_WITH_FILAMENT

bool g_initialized = false;

// P12: last failure description (see Renderer::lastError()). Only written
// on the render thread (the API is single-threaded), so no locking.
std::string g_lastError;

void setLastError(const std::string& message) {
    g_lastError = message;
    if (!message.empty()) {
        std::cerr << "[tiles_renderer] error: " << message << std::endl;
    }
}

} // namespace

bool Renderer::initialize(const RendererConfig& config) {
    if (config.window == nullptr || config.width == 0 || config.height == 0) {
        setLastError("initialize: invalid config "
                     "(need non-null window + nonzero width/height)");
        return false;
    }
    if (g_initialized) {
        setLastError("initialize: already initialized");
        return false;
    }
    setLastError("");

#ifdef TILES_WITH_FILAMENT
    // ---- Real Filament backend (P2 Linux, P4 other platforms) ----
    FilamentState& s = g_state;
    s.engine = filament::Engine::create(TILES_FILAMENT_BACKEND);
    if (s.engine == nullptr) {
        setLastError(std::string("initialize: Engine::create(") +
                     TILES_PLATFORM_NAME + ") failed");
        return false;
    }
    // Native window handle interpretation is platform-specific, but every
    // platform funnels through Engine::createSwapChain(void*):
    //   linux   : X11 Window / wl_surface* (void*)
    //   android : ANativeWindow* (NativeWindowHandle is already that type)
    //   windows : HWND (void*)
    //   ios     : UIView* (void*)
    //   wasm    : canvas CSS selector, e.g. "#canvas" (const char*)
    void* nativeWindow = nullptr;
#if defined(TILES_PLATFORM_WASM)
    const char* canvasSelector = config.window;
    if (canvasSelector == nullptr || canvasSelector[0] == '\0') {
        setLastError("initialize: web backend needs a canvas selector "
                     "(e.g. \"#canvas\")");
        filament::Engine::destroy(s.engine);
        s.engine = nullptr;
        return false;
    }
    // Filament's WebGL platform uses the selector opaquely (never
    // dereferenced as a pointer); the string must outlive the swap chain,
    // so the host must keep it alive (string literals are fine).
    nativeWindow = const_cast<char*>(canvasSelector);
#else
    nativeWindow = reinterpret_cast<void*>(config.window);
#endif
    s.swapChain = s.engine->createSwapChain(nativeWindow);
    if (s.swapChain == nullptr) {
        setLastError("initialize: createSwapChain failed");
        destroyFilamentState();
        return false;
    }
    s.nativeWindow = nativeWindow;
    s.width = config.width;
    s.height = config.height;

    s.renderer = s.engine->createRenderer();
    s.scene = s.engine->createScene();
    s.view = s.engine->createView();
    s.view->setScene(s.scene);
    s.view->setPostProcessingEnabled(false); // faster on software GL; P2 demo

    s.cameraEntity = utils::EntityManager::get().create();
    s.camera = s.engine->createCamera(s.cameraEntity);
    const double aspect =
        static_cast<double>(config.width) / static_cast<double>(config.height);
    s.camera->setProjection(45.0, aspect, 0.1, 100.0);
    s.camera->lookAt({0.0, 0.0, 4.0}, {0.0, 0.0, 0.0}, {0.0, 1.0, 0.0});
    s.view->setCamera(s.camera);
    s.view->setViewport(
        filament::Viewport{0, 0, config.width, config.height});

    filament::Renderer::ClearOptions clearOptions;
    clearOptions.clearColor = {0.1, 0.2, 0.45, 1.0}; // dark blue
    clearOptions.clear = true;
    s.renderer->setClearOptions(clearOptions);

    // P3: a directional "sun" so PBR glTF tile content is lit. It does not
    // affect the P2 unlit triangle material.
    s.sunLight = utils::EntityManager::get().create();
    filament::LightManager::Builder(filament::LightManager::Type::DIRECTIONAL)
        .color({1.0f, 0.98f, 0.95f})
        .intensity(100000.0f)
        .direction({0.0f, -1.0f, 0.35f})
        .build(*s.engine, s.sunLight);
    s.scene->addEntity(s.sunLight);

    // P26: default procedural IBL (on unless the host calls
    // setIblEnabled(false)). A graceful fallback: if the environment can't
    // be built, the scene keeps sun-only lighting.
    {
        default_ibl::BuiltIbl ibl = default_ibl::build(*s.engine);
        if (ibl.light != nullptr) {
            s.ibl = ibl.light;
            s.iblReflections = ibl.reflections;
            s.scene->setIndirectLight(s.ibl);
            std::cout << "[tiles_renderer] IBL enabled (procedural environment)"
                      << std::endl;
        } else {
            std::cout << "[tiles_renderer] IBL unavailable; sun-only lighting"
                      << std::endl;
        }
    }

    // Triangle geometry.
    s.vertexBuffer =
        filament::VertexBuffer::Builder()
            .vertexCount(3)
            .bufferCount(1)
            .attribute(filament::VertexAttribute::POSITION, 0,
                       filament::VertexBuffer::AttributeType::FLOAT3, 0,
                       sizeof(filament::math::float3))
            .build(*s.engine);
    s.vertexBuffer->setBufferAt(
        *s.engine, 0,
        filament::VertexBuffer::BufferDescriptor(kTriangleVerts,
                                                 sizeof(kTriangleVerts)));
    s.indexBuffer = filament::IndexBuffer::Builder()
                        .indexCount(3)
                        .bufferType(filament::IndexBuffer::IndexType::USHORT)
                        .build(*s.engine);
    s.indexBuffer->setBuffer(
        *s.engine,
        filament::IndexBuffer::BufferDescriptor(kTriangleIndices,
                                                sizeof(kTriangleIndices)));

    s.material = filament::Material::Builder()
                     .package(unlit_color_filamat, unlit_color_filamat_len)
                     .build(*s.engine);
    s.materialInstance = s.material->createInstance();
    s.materialInstance->setParameter("color", filament::RgbType::LINEAR,
                                         filament::math::float3{1.0f, 0.0f,
                                                                0.0f}); // pure red

    s.renderable = utils::EntityManager::get().create();
    filament::RenderableManager::Builder(1)
        .boundingBox({{-1.0f, -1.0f, -1.0f}, {1.0f, 1.0f, 1.0f}})
        .material(0, s.materialInstance)
        .geometry(0, filament::RenderableManager::PrimitiveType::TRIANGLES,
                  s.vertexBuffer, s.indexBuffer, 0, 3)
        .culling(false)
        .receiveShadows(false)
        .castShadows(false)
        .build(*s.engine, s.renderable);
    // P3: the P2 triangle is only added to the scene by renderFrame() when no
    // tileset is loaded (keeps the P2 screenshot test pixel-identical).
    s.triangleInScene = false;

    std::cout << "[tiles_renderer] initialized " << config.width << "x"
              << config.height << " (SDK v" << TILES_RENDERER_VERSION << ", "
              << TILES_PLATFORM_NAME << ")" << std::endl;
    g_initialized = true;
    return true;
#else
    // P1 stub path (built without Filament): config validation only.
    std::cout << "[tiles_renderer] initialized " << config.width << "x"
              << config.height << " (SDK v" << TILES_RENDERER_VERSION
              << ", stub: Filament disabled)" << std::endl;
    g_initialized = true;
    return true;
#endif
}

bool Renderer::renderFrame() {
    if (!g_initialized) {
        return false;
    }
#ifdef TILES_WITH_FILAMENT
    FilamentState& s = g_state;
    if (s.engine == nullptr || s.renderer == nullptr || s.swapChain == nullptr) {
        return false;
    }
    // P3: when a tileset is loaded, drive the orbit camera and tile
    // selection/LOD every frame, and hide the P2 triangle.
    const bool useTileset = s.tileset != nullptr && s.tileset->isLoaded();
    if (useTileset) {
        constexpr float kDegToRad = 3.14159265358979323846f / 180.0f;
        const float yaw = s.orbit.yawDegrees * kDegToRad;
        const float pitch = s.orbit.pitchDegrees * kDegToRad;
        const float d = s.orbit.distance;
        // P5: tiles are rendered rebased around the tileset's local origin
        // (world - localOrigin, in double precision), so the Filament camera
        // always orbits (0,0,0) here. Tile *selection* still uses the true
        // world-space origin (see TilesetRenderer::update).
        const filament::math::float3 target{0.0f, 0.0f, 0.0f};
        const filament::math::float3 eye{
            target.x + d * std::cos(pitch) * std::sin(yaw),
            target.y + d * std::sin(pitch),
            target.z + d * std::cos(pitch) * std::cos(yaw)};
        s.camera->lookAt(eye, target, {0.0f, 1.0f, 0.0f});
        s.tileset->update(s.width, s.height, s.orbit);
        if (s.triangleInScene) {
            s.scene->remove(s.renderable);
            s.triangleInScene = false;
        }
    } else if (!s.triangleInScene && s.renderable) {
        s.scene->addEntity(s.renderable);
        s.triangleInScene = true;
    }
    if (s.renderer->beginFrame(s.swapChain)) {
        s.renderer->render(s.view);
        s.renderer->endFrame();
        // Dispatch any pending driver callbacks (e.g. readPixels completion)
        // on this thread, once per frame as Filament recommends.
        s.engine->pumpMessageQueues();
        return true;
    }
    return false; // swap chain not ready (e.g. resized); caller may retry
#else
    return true; // stub path
#endif
}

bool Renderer::readPixels(std::vector<std::uint8_t>& outRgba,
                          std::uint32_t& outWidth, std::uint32_t& outHeight) {
    if (!g_initialized) {
        return false;
    }
#ifdef TILES_WITH_FILAMENT
    FilamentState& s = g_state;
    if (s.engine == nullptr || s.renderer == nullptr || s.swapChain == nullptr ||
        s.width == 0 || s.height == 0) {
        return false;
    }
    outWidth = s.width;
    outHeight = s.height;
    outRgba.assign(outWidth * outHeight * 4u, 0);

    // readPixels() must be issued inside a frame; its callback fires on the
    // main thread after a few more beginFrame/render/endFrame pumps.
    std::atomic<bool> done{false};
    auto onReadback = [](void* /*buffer*/, std::size_t /*size*/, void* user) {
        static_cast<std::atomic<bool>*>(user)->store(true);
    };
    bool issued = false;
    // beginFrame() is non-blocking and may return false if the driver is
    // still busy with the previous frame. Retry briefly before giving up.
    const auto beginDeadline =
        std::chrono::steady_clock::now() + std::chrono::seconds(5);
    while (!issued && std::chrono::steady_clock::now() < beginDeadline) {
        if (s.renderer->beginFrame(s.swapChain)) {
            issued = true;
            s.renderer->render(s.view);
            s.renderer->readPixels(
                0, 0, outWidth, outHeight,
                filament::backend::PixelBufferDescriptor(
                    outRgba.data(), outRgba.size(),
                    filament::backend::PixelBufferDescriptor::PixelDataFormat::
                        RGBA,
                    filament::backend::PixelBufferDescriptor::PixelDataType::
                        UBYTE,
                    onReadback, &done));
            s.renderer->endFrame();
        } else {
            s.engine->pumpMessageQueues();
            std::this_thread::sleep_for(std::chrono::milliseconds(10));
        }
    }
    if (!issued) {
        std::cerr << "[tiles_renderer] readPixels: could not start a frame"
                  << std::endl;
        return false;
    }
    // Pump frames until the read-back callback fires (or we time out).
    // beginFrame() is non-blocking and returns false while the driver is
    // still busy (e.g. software GL), so pace the attempts like a main loop.
    // pumpMessageQueues() dispatches the readPixels completion callback on
    // this thread (Filament queues driver callbacks for the main thread).
    const auto deadline =
        std::chrono::steady_clock::now() + std::chrono::seconds(15);
    while (!done.load() && std::chrono::steady_clock::now() < deadline) {
        s.engine->pumpMessageQueues();
        if (done.load()) {
            break;
        }
        if (s.renderer->beginFrame(s.swapChain)) {
            s.renderer->render(s.view);
            s.renderer->endFrame();
        } else {
            std::this_thread::sleep_for(std::chrono::milliseconds(4));
        }
    }
    if (!done.load()) {
        std::cerr << "[tiles_renderer] readPixels: timed out waiting for "
                     "read-back" << std::endl;
        return false;
    }
    return true;
#else
    (void)outRgba;
    (void)outWidth;
    (void)outHeight;
    return false; // stub path: nothing rendered
#endif
}

void Renderer::shutdown() {
#ifdef TILES_WITH_FILAMENT
    // P3: destroy the tileset first — tile teardown calls free(), which
    // needs a live Filament engine/scene.
    g_state.tileset.reset();
    destroyFilamentState();
#endif
    g_initialized = false;
    std::cout << "[tiles_renderer] shutdown" << std::endl;
}

bool Renderer::loadTileset(const std::string& tilesetUrl) {
    if (!g_initialized) {
        setLastError("loadTileset: not initialized");
        return false;
    }
    setLastError("");
#ifdef TILES_WITH_FILAMENT
    FilamentState& s = g_state;
    if (s.engine == nullptr || s.scene == nullptr) {
        setLastError("loadTileset: engine not ready");
        return false;
    }
    auto tileset = std::make_unique<TilesetRenderer>(s.engine, s.scene);
    // P19: apply a budget set before load (no-op when never set).
    tileset->setMaxCachedBytes(g_pendingMaxCachedBytes);
    // P22: build-then-commit. The new TilesetRenderer is fully loaded
    // before it replaces the old one, so a failed loadTileset() (bad
    // path, corrupt tileset.json, timeout) leaves the currently-loaded
    // tileset untouched and rendering. The old code reset s.tileset up
    // front, destroying the working tileset even when the new load failed.
    if (!tileset->load(tilesetUrl)) {
        setLastError("loadTileset: " + tileset->lastError());
        return false;
    }
    s.tileset.reset(); // drop the previous tileset only on success
    s.tileset = std::move(tileset);
    return true;
#else
    (void)tilesetUrl;
    setLastError("loadTileset: not available in this build");
    return false;
#endif
}

bool Renderer::resize(std::uint32_t width, std::uint32_t height) {
    if (!g_initialized) {
        setLastError("resize: not initialized");
        return false;
    }
    if (width == 0 || height == 0) {
        setLastError("resize: dimensions must be nonzero");
        return false;
    }
    setLastError("");
#ifdef TILES_WITH_FILAMENT
    FilamentState& s = g_state;
    if (s.engine == nullptr || s.swapChain == nullptr ||
        s.nativeWindow == nullptr) {
        setLastError("resize: engine not ready");
        return false;
    }
    if (width == s.width && height == s.height) {
        return true; // no-op
    }
    // Recreate the swap chain for the same native window (the host owns the
    // window and is responsible for resizing the OS-level surface first).
    // Called between frames on the render thread, so no in-flight frame is
    // using the old swap chain.
    s.engine->destroy(s.swapChain);
    s.swapChain = s.engine->createSwapChain(s.nativeWindow);
    if (s.swapChain == nullptr) {
        setLastError("resize: createSwapChain failed");
        return false;
    }
    s.width = width;
    s.height = height;
    s.view->setViewport(filament::Viewport{0, 0, width, height});
    const double aspect = static_cast<double>(width) / static_cast<double>(height);
    s.camera->setProjection(45.0, aspect, 0.1, 100.0);
    std::cout << "[tiles_renderer] resized to " << width << "x" << height
              << std::endl;
    return true;
#else
    return true; // stub path: nothing to resize
#endif
}

std::string Renderer::lastError() {
    return g_lastError;
}

void Renderer::setOrbitCamera(
    float yawDegrees, float pitchDegrees, float distance) {
    if (!g_initialized) {
        return;
    }
#ifdef TILES_WITH_FILAMENT
    g_state.orbit.yawDegrees = yawDegrees;
    g_state.orbit.pitchDegrees = pitchDegrees;
    g_state.orbit.distance = distance;
#else
    (void)yawDegrees;
    (void)pitchDegrees;
    (void)distance;
#endif
}

int Renderer::renderedTileCount() {
    if (!g_initialized) {
        return -1;
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset == nullptr) {
        return -1;
    }
    return g_state.tileset->renderedTileCount();
#else
    return -1;
#endif
}

Renderer::TileStats Renderer::tileStats() {
    if (!g_initialized) {
        return TileStats{}; // all -1
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset == nullptr) {
        return TileStats{}; // all -1
    }
    return g_state.tileset->tileStats();
#else
    return TileStats{};
#endif
}

std::vector<std::string> Renderer::selectedTileIds() {
    if (!g_initialized) {
        return {};
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset == nullptr) {
        return {};
    }
    return g_state.tileset->selectedTileIds();
#else
    return {};
#endif
}

const char* Renderer::version() {
    return TILES_RENDERER_VERSION;
}

void Renderer::setMaxCachedBytes(std::int64_t bytes) {
    if (!g_initialized) {
        return;
    }
    // Stash: applies to the next loadTileset() even when no tileset is
    // loaded yet. Forward live when one is.
    g_pendingMaxCachedBytes = bytes;
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->setMaxCachedBytes(bytes);
    }
#endif
}

// P26: toggle the default procedural IBL. Cheap: only attaches/detaches the
// IndirectLight built once at initialize(); the cubemap and SH survive the
// session. No-op when IBL failed to build (sun-only fallback).
void Renderer::setIblEnabled(bool enabled) {
    if (!g_initialized) {
        return;
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.ibl == nullptr || g_state.scene == nullptr) {
        return;
    }
    if (g_state.iblEnabled == enabled) {
        return;
    }
    g_state.iblEnabled = enabled;
    g_state.scene->setIndirectLight(enabled ? g_state.ibl : nullptr);
    std::cout << "[tiles_renderer] IBL " << (enabled ? "enabled" : "disabled")
              << std::endl;
#else
    (void)enabled;
#endif
}

} // namespace tiles_renderer
