// tiles_renderer SDK implementation.
//
// P2: real Filament rendering on Linux (OpenGL backend, native X11/Wayland
// window handle). P4: the same engine/scene/view code now runs on Android
// (Vulkan + ANativeWindow), Windows (Vulkan + HWND), iOS (Metal + UIView)
// and Web (WebGL + canvas selector) — only the backend enum and the native
// handle interpretation differ per platform (see TILES_FILAMENT_BACKEND).

#include "tiles_renderer/renderer.h"

#include "tiles_renderer/version.h"
#include "tileset_internal.h"

#include <atomic>
#include <chrono>
#include <iostream>
#include <memory>
#include <thread>

#ifdef TILES_WITH_FILAMENT
#include <backend/PixelBufferDescriptor.h>
#include <filament/Camera.h>
#include <filament/Engine.h>
#include <filament/IndexBuffer.h>
#include <filament/LightManager.h>
#include <filament/Material.h>
#include <filament/RenderableManager.h>
#include <filament/Renderer.h>
#include <filament/Scene.h>
#include <filament/SwapChain.h>
#include <filament/VertexBuffer.h>
#include <filament/View.h>
#include <filament/Viewport.h>
#include <utils/EntityManager.h>

#include "unlit_color_filamat.h" // generated by cmake/embed_filamat.py (matc)
#endif

// P4: platform backend selection. TILES_PLATFORM_* is defined by CMake from
// the TILES_PLATFORM cache variable, so the choice follows the *target*
// platform rather than host compiler macros (matters for cross builds).
//
// Backend choice follows what each official Filament prebuilt ships:
//   linux   : OpenGL (X11 Window / wl_surface* as void*)
//   android : Vulkan (ANativeWindow*; android prebuilt ships bluevk only)
//   windows : Vulkan (HWND)
//   ios     : Metal (UIView*)
//   wasm    : default backend (WebGL); nativeWindow is the canvas CSS
//             selector string, used opaquely (see Filament jsbindings
//             _createSwapChainForCanvas)
#ifdef TILES_WITH_FILAMENT
#if defined(TILES_PLATFORM_ANDROID)
#define TILES_FILAMENT_BACKEND filament::Engine::Backend::VULKAN
#define TILES_PLATFORM_NAME "Android/Vulkan"
#elif defined(TILES_PLATFORM_WINDOWS)
#define TILES_FILAMENT_BACKEND filament::Engine::Backend::VULKAN
#define TILES_PLATFORM_NAME "Windows/Vulkan"
#elif defined(TILES_PLATFORM_IOS)
#define TILES_FILAMENT_BACKEND filament::Engine::Backend::METAL
#define TILES_PLATFORM_NAME "iOS/Metal"
#elif defined(TILES_PLATFORM_WASM)
#define TILES_FILAMENT_BACKEND filament::Engine::Backend::DEFAULT
#define TILES_PLATFORM_NAME "Web/WebGL"
#elif defined(TILES_PLATFORM_LINUX)
#define TILES_FILAMENT_BACKEND filament::Engine::Backend::OPENGL
#define TILES_PLATFORM_NAME "Linux/OpenGL"
#else
#error "TILES_PLATFORM_*: unknown target platform (expected CMake to define one)"
#endif
#endif // TILES_WITH_FILAMENT

namespace tiles_renderer {
namespace {

#ifdef TILES_WITH_FILAMENT

// P19: cache budget set before any tileset is loaded is stashed here and
// applied in loadTileset() before the cesium Tileset is constructed.
std::int64_t g_pendingMaxCachedBytes = -1;

// P2 demo geometry: a single triangle. Static storage so the Filament buffer
// descriptors never dangle.
constexpr filament::math::float3 kTriangleVerts[3] = {
    {-0.6f, -0.5f, 0.0f},
    {0.6f, -0.5f, 0.0f},
    {0.0f, 0.6f, 0.0f},
};
constexpr std::uint16_t kTriangleIndices[3] = {0, 1, 2};

struct FilamentState {
    filament::Engine* engine = nullptr;
    filament::SwapChain* swapChain = nullptr;
    filament::Renderer* renderer = nullptr; // filament::Renderer (not this SDK class)
    filament::Scene* scene = nullptr;
    filament::View* view = nullptr;
    filament::Camera* camera = nullptr;
    utils::Entity cameraEntity{};
    utils::Entity renderable{};
    filament::VertexBuffer* vertexBuffer = nullptr;
    filament::IndexBuffer* indexBuffer = nullptr;
    filament::Material* material = nullptr;
    filament::MaterialInstance* materialInstance = nullptr;
    std::uint32_t width = 0;
    std::uint32_t height = 0;
    // P12: the native window handle passed to initialize(), kept so resize()
    // can recreate the swap chain for the same window. For WASM this points
    // at the host's canvas-selector string (host must keep it alive — same
    // rule as in initialize()).
    void* nativeWindow = nullptr;
    // P3: optional tileset integration (null when no tileset loaded).
    std::unique_ptr<TilesetRenderer> tileset;
    OrbitCamera orbit;
    utils::Entity sunLight{};
    bool triangleInScene = false;
};

FilamentState g_state;

void destroyFilamentState() {
    FilamentState& s = g_state;
    if (s.engine == nullptr) {
        return;
    }
    // Destroy user resources first, engine last (Filament requirement).
    if (s.sunLight) {
        s.scene->remove(s.sunLight);
        s.engine->destroy(s.sunLight);
        utils::EntityManager::get().destroy(s.sunLight);
        s.sunLight.clear();
    }
    if (s.renderable) {
        if (s.triangleInScene) {
            s.scene->remove(s.renderable);
            s.triangleInScene = false;
        }
        s.engine->destroy(s.renderable);
        utils::EntityManager::get().destroy(s.renderable);
        s.renderable.clear();
    }
    if (s.materialInstance) {
        s.engine->destroy(s.materialInstance);
        s.materialInstance = nullptr;
    }
    if (s.material) {
        s.engine->destroy(s.material);
        s.material = nullptr;
    }
    if (s.vertexBuffer) {
        s.engine->destroy(s.vertexBuffer);
        s.vertexBuffer = nullptr;
    }
    if (s.indexBuffer) {
        s.engine->destroy(s.indexBuffer);
        s.indexBuffer = nullptr;
    }
    if (s.cameraEntity) {
        s.engine->destroyCameraComponent(s.cameraEntity);
        utils::EntityManager::get().destroy(s.cameraEntity);
        s.cameraEntity.clear();
        s.camera = nullptr;
    }
    if (s.view) {
        s.engine->destroy(s.view);
        s.view = nullptr;
    }
    if (s.scene) {
        s.engine->destroy(s.scene);
        s.scene = nullptr;
    }
    // Filament docs: destroy in reverse creation order —
    // view, scene, renderer, swapChain, engine last.
    if (s.renderer) {
        s.engine->destroy(s.renderer);
        s.renderer = nullptr;
    }
    if (s.swapChain) {
        s.engine->destroy(s.swapChain);
        s.swapChain = nullptr;
    }
    filament::Engine::destroy(s.engine);
    s.engine = nullptr;
    s.width = s.height = 0;
}

#endif // TILES_WITH_FILAMENT

bool g_initialized = false;

// P12: last failure description (see Renderer::lastError()). Only written
// on the render thread (the API is single-threaded), so no locking.
std::string g_lastError;

void setLastError(const std::string& message) {
    g_lastError = message;
    if (!message.empty()) {
        std::cerr << "[tiles_renderer] error: " << message << std::endl;
    }
}

} // namespace

bool Renderer::initialize(const RendererConfig& config) {
    if (config.window == nullptr || config.width == 0 || config.height == 0) {
        setLastError("initialize: invalid config "
                     "(need non-null window + nonzero width/height)");
        return false;
    }
    if (g_initialized) {
        setLastError("initialize: already initialized");
        return false;
    }
    setLastError("");

#ifdef TILES_WITH_FILAMENT
    // ---- Real Filament backend (P2 Linux, P4 other platforms) ----
    FilamentState& s = g_state;
    s.engine = filament::Engine::create(TILES_FILAMENT_BACKEND);
    if (s.engine == nullptr) {
        setLastError(std::string("initialize: Engine::create(") +
                     TILES_PLATFORM_NAME + ") failed");
        return false;
    }
    // Native window handle interpretation is platform-specific, but every
    // platform funnels through Engine::createSwapChain(void*):
    //   linux   : X11 Window / wl_surface* (void*)
    //   android : ANativeWindow* (NativeWindowHandle is already that type)
    //   windows : HWND (void*)
    //   ios     : UIView* (void*)
    //   wasm    : canvas CSS selector, e.g. "#canvas" (const char*)
    void* nativeWindow = nullptr;
#if defined(TILES_PLATFORM_WASM)
    const char* canvasSelector = config.window;
    if (canvasSelector == nullptr || canvasSelector[0] == '\0') {
        setLastError("initialize: web backend needs a canvas selector "
                     "(e.g. \"#canvas\")");
        filament::Engine::destroy(s.engine);
        s.engine = nullptr;
        return false;
    }
    // Filament's WebGL platform uses the selector opaquely (never
    // dereferenced as a pointer); the string must outlive the swap chain,
    // so the host must keep it alive (string literals are fine).
    nativeWindow = const_cast<char*>(canvasSelector);
#else
    nativeWindow = reinterpret_cast<void*>(config.window);
#endif
    s.swapChain = s.engine->createSwapChain(nativeWindow);
    if (s.swapChain == nullptr) {
        setLastError("initialize: createSwapChain failed");
        destroyFilamentState();
        return false;
    }
    s.nativeWindow = nativeWindow;
    s.width = config.width;
    s.height = config.height;

    s.renderer = s.engine->createRenderer();
    s.scene = s.engine->createScene();
    s.view = s.engine->createView();
    s.view->setScene(s.scene);
    s.view->setPostProcessingEnabled(false); // faster on software GL; P2 demo

    s.cameraEntity = utils::EntityManager::get().create();
    s.camera = s.engine->createCamera(s.cameraEntity);
    const double aspect =
        static_cast<double>(config.width) / static_cast<double>(config.height);
    s.camera->setProjection(45.0, aspect, 0.1, 100.0);
    s.camera->lookAt({0.0, 0.0, 4.0}, {0.0, 0.0, 0.0}, {0.0, 1.0, 0.0});
    s.view->setCamera(s.camera);
    s.view->setViewport(
        filament::Viewport{0, 0, config.width, config.height});

    filament::Renderer::ClearOptions clearOptions;
    clearOptions.clearColor = {0.1, 0.2, 0.45, 1.0}; // dark blue
    clearOptions.clear = true;
    s.renderer->setClearOptions(clearOptions);

    // P3: a directional "sun" so PBR glTF tile content is lit. It does not
    // affect the P2 unlit triangle material.
    s.sunLight = utils::EntityManager::get().create();
    filament::LightManager::Builder(filament::LightManager::Type::DIRECTIONAL)
        .color({1.0f, 0.98f, 0.95f})
        .intensity(100000.0f)
        .direction({0.0f, -1.0f, 0.35f})
        .build(*s.engine, s.sunLight);
    s.scene->addEntity(s.sunLight);

    // Triangle geometry.
    s.vertexBuffer =
        filament::VertexBuffer::Builder()
            .vertexCount(3)
            .bufferCount(1)
            .attribute(filament::VertexAttribute::POSITION, 0,
                       filament::VertexBuffer::AttributeType::FLOAT3, 0,
                       sizeof(filament::math::float3))
            .build(*s.engine);
    s.vertexBuffer->setBufferAt(
        *s.engine, 0,
        filament::VertexBuffer::BufferDescriptor(kTriangleVerts,
                                                 sizeof(kTriangleVerts)));
    s.indexBuffer = filament::IndexBuffer::Builder()
                        .indexCount(3)
                        .bufferType(filament::IndexBuffer::IndexType::USHORT)
                        .build(*s.engine);
    s.indexBuffer->setBuffer(
        *s.engine,
        filament::IndexBuffer::BufferDescriptor(kTriangleIndices,
                                                sizeof(kTriangleIndices)));

    s.material = filament::Material::Builder()
                     .package(unlit_color_filamat, unlit_color_filamat_len)
                     .build(*s.engine);
    s.materialInstance = s.material->createInstance();
    s.materialInstance->setParameter("color", filament::RgbType::LINEAR,
                                         filament::math::float3{1.0f, 0.0f,
                                                                0.0f}); // pure red

    s.renderable = utils::EntityManager::get().create();
    filament::RenderableManager::Builder(1)
        .boundingBox({{-1.0f, -1.0f, -1.0f}, {1.0f, 1.0f, 1.0f}})
        .material(0, s.materialInstance)
        .geometry(0, filament::RenderableManager::PrimitiveType::TRIANGLES,
                  s.vertexBuffer, s.indexBuffer, 0, 3)
        .culling(false)
        .receiveShadows(false)
        .castShadows(false)
        .build(*s.engine, s.renderable);
    // P3: the P2 triangle is only added to the scene by renderFrame() when no
    // tileset is loaded (keeps the P2 screenshot test pixel-identical).
    s.triangleInScene = false;

    std::cout << "[tiles_renderer] initialized " << config.width << "x"
              << config.height << " (SDK v" << TILES_RENDERER_VERSION << ", "
              << TILES_PLATFORM_NAME << ")" << std::endl;
    g_initialized = true;
    return true;
#else
    // P1 stub path (built without Filament): config validation only.
    std::cout << "[tiles_renderer] initialized " << config.width << "x"
              << config.height << " (SDK v" << TILES_RENDERER_VERSION
              << ", stub: Filament disabled)" << std::endl;
    g_initialized = true;
    return true;
#endif
}

bool Renderer::renderFrame() {
    if (!g_initialized) {
        return false;
    }
#ifdef TILES_WITH_FILAMENT
    FilamentState& s = g_state;
    if (s.engine == nullptr || s.renderer == nullptr || s.swapChain == nullptr) {
        return false;
    }
    // P3: when a tileset is loaded, drive the orbit camera and tile
    // selection/LOD every frame, and hide the P2 triangle.
    const bool useTileset = s.tileset != nullptr && s.tileset->isLoaded();
    if (useTileset) {
        constexpr float kDegToRad = 3.14159265358979323846f / 180.0f;
        const float yaw = s.orbit.yawDegrees * kDegToRad;
        const float pitch = s.orbit.pitchDegrees * kDegToRad;
        const float d = s.orbit.distance;
        // P5: tiles are rendered rebased around the tileset's local origin
        // (world - localOrigin, in double precision), so the Filament camera
        // always orbits (0,0,0) here. Tile *selection* still uses the true
        // world-space origin (see TilesetRenderer::update).
        const filament::math::float3 target{0.0f, 0.0f, 0.0f};
        const filament::math::float3 eye{
            target.x + d * std::cos(pitch) * std::sin(yaw),
            target.y + d * std::sin(pitch),
            target.z + d * std::cos(pitch) * std::cos(yaw)};
        s.camera->lookAt(eye, target, {0.0f, 1.0f, 0.0f});
        s.tileset->update(s.width, s.height, s.orbit);
        if (s.triangleInScene) {
            s.scene->remove(s.renderable);
            s.triangleInScene = false;
        }
    } else if (!s.triangleInScene && s.renderable) {
        s.scene->addEntity(s.renderable);
        s.triangleInScene = true;
    }
    if (s.renderer->beginFrame(s.swapChain)) {
        s.renderer->render(s.view);
        s.renderer->endFrame();
        // Dispatch any pending driver callbacks (e.g. readPixels completion)
        // on this thread, once per frame as Filament recommends.
        s.engine->pumpMessageQueues();
        return true;
    }
    return false; // swap chain not ready (e.g. resized); caller may retry
#else
    return true; // stub path
#endif
}

bool Renderer::readPixels(std::vector<std::uint8_t>& outRgba,
                          std::uint32_t& outWidth, std::uint32_t& outHeight) {
    if (!g_initialized) {
        return false;
    }
#ifdef TILES_WITH_FILAMENT
    FilamentState& s = g_state;
    if (s.engine == nullptr || s.renderer == nullptr || s.swapChain == nullptr ||
        s.width == 0 || s.height == 0) {
        return false;
    }
    outWidth = s.width;
    outHeight = s.height;
    outRgba.assign(outWidth * outHeight * 4u, 0);

    // readPixels() must be issued inside a frame; its callback fires on the
    // main thread after a few more beginFrame/render/endFrame pumps.
    std::atomic<bool> done{false};
    auto onReadback = [](void* /*buffer*/, std::size_t /*size*/, void* user) {
        static_cast<std::atomic<bool>*>(user)->store(true);
    };
    bool issued = false;
    // beginFrame() is non-blocking and may return false if the driver is
    // still busy with the previous frame. Retry briefly before giving up.
    const auto beginDeadline =
        std::chrono::steady_clock::now() + std::chrono::seconds(5);
    while (!issued && std::chrono::steady_clock::now() < beginDeadline) {
        if (s.renderer->beginFrame(s.swapChain)) {
            issued = true;
            s.renderer->render(s.view);
            s.renderer->readPixels(
                0, 0, outWidth, outHeight,
                filament::backend::PixelBufferDescriptor(
                    outRgba.data(), outRgba.size(),
                    filament::backend::PixelBufferDescriptor::PixelDataFormat::
                        RGBA,
                    filament::backend::PixelBufferDescriptor::PixelDataType::
                        UBYTE,
                    onReadback, &done));
            s.renderer->endFrame();
        } else {
            s.engine->pumpMessageQueues();
            std::this_thread::sleep_for(std::chrono::milliseconds(10));
        }
    }
    if (!issued) {
        std::cerr << "[tiles_renderer] readPixels: could not start a frame"
                  << std::endl;
        return false;
    }
    // Pump frames until the read-back callback fires (or we time out).
    // beginFrame() is non-blocking and returns false while the driver is
    // still busy (e.g. software GL), so pace the attempts like a main loop.
    // pumpMessageQueues() dispatches the readPixels completion callback on
    // this thread (Filament queues driver callbacks for the main thread).
    const auto deadline =
        std::chrono::steady_clock::now() + std::chrono::seconds(15);
    while (!done.load() && std::chrono::steady_clock::now() < deadline) {
        s.engine->pumpMessageQueues();
        if (done.load()) {
            break;
        }
        if (s.renderer->beginFrame(s.swapChain)) {
            s.renderer->render(s.view);
            s.renderer->endFrame();
        } else {
            std::this_thread::sleep_for(std::chrono::milliseconds(4));
        }
    }
    if (!done.load()) {
        std::cerr << "[tiles_renderer] readPixels: timed out waiting for "
                     "read-back" << std::endl;
        return false;
    }
    return true;
#else
    (void)outRgba;
    (void)outWidth;
    (void)outHeight;
    return false; // stub path: nothing rendered
#endif
}

void Renderer::shutdown() {
#ifdef TILES_WITH_FILAMENT
    // P3: destroy the tileset first — tile teardown calls free(), which
    // needs a live Filament engine/scene.
    g_state.tileset.reset();
    destroyFilamentState();
#endif
    g_initialized = false;
    std::cout << "[tiles_renderer] shutdown" << std::endl;
}

bool Renderer::loadTileset(const std::string& tilesetUrl) {
    if (!g_initialized) {
        setLastError("loadTileset: not initialized");
        return false;
    }
    setLastError("");
#ifdef TILES_WITH_FILAMENT
    FilamentState& s = g_state;
    if (s.engine == nullptr || s.scene == nullptr) {
        setLastError("loadTileset: engine not ready");
        return false;
    }
    auto tileset = std::make_unique<TilesetRenderer>(s.engine, s.scene);
    // P19: apply a budget set before load (no-op when never set).
    tileset->setMaxCachedBytes(g_pendingMaxCachedBytes);
    // P22: build-then-commit. The new TilesetRenderer is fully loaded
    // before it replaces the old one, so a failed loadTileset() (bad
    // path, corrupt tileset.json, timeout) leaves the currently-loaded
    // tileset untouched and rendering. The old code reset s.tileset up
    // front, destroying the working tileset even when the new load failed.
    if (!tileset->load(tilesetUrl)) {
        setLastError("loadTileset: " + tileset->lastError());
        return false;
    }
    s.tileset.reset(); // drop the previous tileset only on success
    s.tileset = std::move(tileset);
    return true;
#else
    (void)tilesetUrl;
    setLastError("loadTileset: not available in this build");
    return false;
#endif
}

bool Renderer::resize(std::uint32_t width, std::uint32_t height) {
    if (!g_initialized) {
        setLastError("resize: not initialized");
        return false;
    }
    if (width == 0 || height == 0) {
        setLastError("resize: dimensions must be nonzero");
        return false;
    }
    setLastError("");
#ifdef TILES_WITH_FILAMENT
    FilamentState& s = g_state;
    if (s.engine == nullptr || s.swapChain == nullptr ||
        s.nativeWindow == nullptr) {
        setLastError("resize: engine not ready");
        return false;
    }
    if (width == s.width && height == s.height) {
        return true; // no-op
    }
    // Recreate the swap chain for the same native window (the host owns the
    // window and is responsible for resizing the OS-level surface first).
    // Called between frames on the render thread, so no in-flight frame is
    // using the old swap chain.
    s.engine->destroy(s.swapChain);
    s.swapChain = s.engine->createSwapChain(s.nativeWindow);
    if (s.swapChain == nullptr) {
        setLastError("resize: createSwapChain failed");
        return false;
    }
    s.width = width;
    s.height = height;
    s.view->setViewport(filament::Viewport{0, 0, width, height});
    const double aspect = static_cast<double>(width) / static_cast<double>(height);
    s.camera->setProjection(45.0, aspect, 0.1, 100.0);
    std::cout << "[tiles_renderer] resized to " << width << "x" << height
              << std::endl;
    return true;
#else
    return true; // stub path: nothing to resize
#endif
}

std::string Renderer::lastError() {
    return g_lastError;
}

void Renderer::setOrbitCamera(
    float yawDegrees, float pitchDegrees, float distance) {
    if (!g_initialized) {
        return;
    }
#ifdef TILES_WITH_FILAMENT
    g_state.orbit.yawDegrees = yawDegrees;
    g_state.orbit.pitchDegrees = pitchDegrees;
    g_state.orbit.distance = distance;
#else
    (void)yawDegrees;
    (void)pitchDegrees;
    (void)distance;
#endif
}

int Renderer::renderedTileCount() {
    if (!g_initialized) {
        return -1;
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset == nullptr) {
        return -1;
    }
    return g_state.tileset->renderedTileCount();
#else
    return -1;
#endif
}

Renderer::TileStats Renderer::tileStats() {
    if (!g_initialized) {
        return TileStats{}; // all -1
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset == nullptr) {
        return TileStats{}; // all -1
    }
    return g_state.tileset->tileStats();
#else
    return TileStats{};
#endif
}

std::vector<std::string> Renderer::selectedTileIds() {
    if (!g_initialized) {
        return {};
    }
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset == nullptr) {
        return {};
    }
    return g_state.tileset->selectedTileIds();
#else
    return {};
#endif
}

const char* Renderer::version() {
    return TILES_RENDERER_VERSION;
}

void Renderer::setMaxCachedBytes(std::int64_t bytes) {
    if (!g_initialized) {
        return;
    }
    // Stash: applies to the next loadTileset() even when no tileset is
    // loaded yet. Forward live when one is.
    g_pendingMaxCachedBytes = bytes;
#ifdef TILES_WITH_FILAMENT
    if (g_state.tileset != nullptr) {
        g_state.tileset->setMaxCachedBytes(bytes);
    }
#endif
}

} // namespace tiles_renderer
