#!/usr/bin/env python3
"""Embed a .filamat binary as a C++ header (byte array).

Usage: embed_filamat.py <input.filamat> <output.h> <symbol_name>
"""
import sys


def main() -> int:
    src, dst, symbol = sys.argv[1], sys.argv[2], sys.argv[3]
    with open(src, "rb") as f:
        data = f.read()
    lines = []
    lines.append("// Generated by cmake/embed_filamat.py — do not edit.")
    lines.append("#pragma once")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append(f"static const unsigned char {symbol}[] = {{")
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"static const std::size_t {symbol}_len = sizeof({symbol});")
    lines.append("")
    with open(dst, "w") as f:
        f.write("\n".join(lines))
    print(f"[embed_filamat] {src} -> {dst} ({len(data)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
